### ISSUE TITLE
"upper pane" layout strategy?

### ISSUE THREAD

**Issue by ExpandingMan** [nvim-telescope/telescope.nvim#1043]
I kind of prefer the `bottom_pane` "ivy" layout strategy, but I have information on my status line that I don't really want to hide while I'm searching.  Is there a way to "invert" it and put it on the top?

Also, the ability to move the search windows to the sides would also be great.

Apologies if this is redundant, I did a quick search and don't think I saw an equivalent issue.

**Comment by elianiva** [comment]
You'll need to make a new theme, there isn't an option flag to move the position. Should be relatively easy, I think.

**Comment by l-kershaw** [comment]
Just to clarify, you'd need to make a new **`layout_strategy`** for the `upper_pane` (somewhere in [this](https://github.com/nvim-telescope/telescope.nvim/blob/master/lua/telescope/pickers/layout_strategies.lua) file).
Once you've done that, it would be pretty easy to create an `upper_ivy` theme (not sure if there's a better name?) that incorporates this by basically duplicating the `ivy` theme [here](https://github.com/nvim-telescope/telescope.nvim/blob/c0f1999b0280bb042bba01c930dd94a4bfdee363/lua/telescope/themes.lua#L108), then changing the `layout_strategy` to `upper_pane` instead of `lower_pane`.

**Comment by l-kershaw** [comment]
@ExpandingMan after the recent `layout_strategy` refactor, the `bottom_pane` strategy does not cover your status line.
Since that was your reason for requesting an `upper_pane` strategy, I will close this issue.

Feel free to reopen if this is not a satisfactory solution for you 🙂
