### ISSUE TITLE
Find_files in subdirectories and `n` parent directories.

### ISSUE THREAD

**Issue by abd96** [nvim-telescope/telescope.nvim#1063]
**Is your feature request related to a problem? Please describe.**
I have the find_files option of telescope mapped to `<C-f>` and when I use it on a current opened file, it only shows the files 
starting from the current directory. So I cannot search files in one or two upper directories. Searching files n directories backwards and forwards is very helpful for me when I have projects with a lot of subdirectories and I want to switch fast between files.

**Describe the solution you'd like**
I would like to define `n` let's say equals 2 and whenever I use find_files the search results will not only show from directories starting at current directory but also from `n` parent directories. Is this already implemented ? How can I define such a behavior?

**Comment by l-kershaw** [comment]
I don't think that this is something that we would include in telescope, but it is something that you can configure yourself using telescope and plenary.
For example:
```
local Path = require"plenary.path"
local builtin = require"telescope.builtin"
local parent_find_files = function(n)
  local cwd = Path:new(vim.loop.cwd())
  for _ = 1, n do
    cwd = cwd:parent()
  end
  cwd = cwd:absolute()
  builtin.find_files({cwd = cwd})
end
```
calling this function with `n=2` will do what you want.

**Comment by abd96** [comment]
Thank you for the code snippet. I tried adding this to myvimrc  and getting this error after `:so %` and calling the function with `n=2`

`E5108: Error executing lua [string ":lua"]:79: attempt to call method 'parent' (a nil value) `

Calling the function with `1` shows 
`E5108: Error executing lua [string ":lua"]:79: attempt to call method 'absolute' (a nil value) `

**Comment by l-kershaw** [comment]
I think that you don't have an up to date version of plenary. It was updated yesterday to make `Path:parent` return a `Path` object, where it previously returned a string.
Try updating plenary, and let me know if you are still having any issues 🙂

**Comment by abd96** [comment]
That did actually work, thank you! But I am struggling in mapping `parent_find_files` to `<C-f>`. My original vim code for mapping : 
` nnoremap <C-f> <cmd>Telescope find_files<cr>`

Now I tried this : `vim.api.nvim_set_keymap('n',  '<C-f>', "parent_find_fileS(2)", { noremap=true,  silent=true} )` but that's only printing `arent_find_files(2)` when pressing `<C-f>`

**Comment by l-kershaw** [comment]
The first issue here is that this is a command that will be run as a normal vimscript command, but we want to call a lua function, so we should start our command with `:lua`, so that we can call a lua function.

Secondly, we need to be aware of the scope of the function that we are trying to call, and the current scope when we are running our command. If the function is not in the current scope then we won't be able to call it.
To get around this problem, I would suggest creating a file in your config in the lua folder, e.g. `lua/abd.lua`.
In this file we want to put this function, but we also want to return it in an accessible way. For example something like this
``` lua
local Path = require"plenary.path"
local builtin = require"telescope.builtin"

local M = {}
M.parent_find_files = function(n)
  local cwd = Path:new(vim.loop.cwd())
  for _ = 1, n do
    cwd = cwd:parent()
  end
  cwd = cwd:absolute()
  builtin.find_files({cwd = cwd})
end

return M
```
This then means that when we call `require('abd')`, we will be returned a table with the function we want in an accessible way.
We can then change our mapping to
``` lua
vim.api.nvim_set_keymap('n', '<C-f>', ":lua require('abd').parent_find_files(2)", { noremap=true, silent=true} )
```
Then when we call our mapping, it enters command mode (the `:`), prepares to call lua (the `lua`), runs our custom file (the `require('abd')`), which returns a table of values, one of which we want to access (the `.parent_find_files`). This gives us a function, which we then want to call with the parameter `2`.

I hope this makes sense 😅 
Let me know if you are still having any issues 🙂

**Comment by abd96** [comment]
Thank you for this explanation, that did work as expected :)

**Comment by l-kershaw** [comment]
Glad it's working for you 👍

Closing now
