### ISSUE TITLE
Proposal: Extension Specific Config Options? 

### ISSUE THREAD

**Issue by glyh** [nvim-telescope/telescope.nvim#1065]
**Is your feature request related to a problem? Please describe.**

There are a bunch of extensions of telescope avaliable, but maybe they don't provide good interfaces to end-users. 

For example, I have 2 extensions, A and B on telescope. The key mappings or other configs in init.lua for A and B are different.

Then I can't config some of them via :Telescope command, for example: the previewers are functions, which expect some functions to passed to it. 

**Describe the solution you'd like**

Provide extension specific configs. i.e. have different setup functions for different extensions. Their default behavoirs inherit from the default setup. 

**Describe alternatives you've considered**

Ask extension writer to provide the functions. But I think this is a general need, and thus should be added to the core telescope.nvim.

**Comment by Conni2461** [comment]
I am not sure what you mean but we have extension specific config. Example: https://github.com/nvim-telescope/telescope-fzf-native.nvim#telescope-setup-and-configuration or https://github.com/nvim-telescope/telescope-frecency.nvim#example-configuration

I am currently reworking the docs to make stuff more clear

> Then I can't config some of them via :Telescope command, for example: the previewers are functions, which expect some functions to passed to it.

You should use the lua interface, because you will never be able to pass in a function with the vim interface. `require("telescope.builtin").find_files({previewer= function() ... end})`

You can also access extensions with `require("telescope").extensions`. Try `print(vim.inspect(require("telescope").extensions))` then you can call the same function as `:Telescope extension command` does

**Comment by Conni2461** [comment]
Stale closing.
