### ISSUE TITLE
dynamic_preview_title affected by prompt window width

### ISSUE THREAD

**Issue by againxx** [nvim-telescope/telescope.nvim#1096]
### Description

The previewer title does not align well for long filename
**Expected Behavior**

The title corner should align with the vertical line
**Actual Behavior**

There is a noticeable gap between the title border and the right vertical border
### Details
![image](https://user-images.githubusercontent.com/22728604/128853588-8b9ce3e3-4a63-4cb8-9839-17932fcde65c.png)

I think the problem may come from we use `strdisplaywidth()` to compute title length, however this computation happens in the prompt window, which may be shorter than preview window, and the `showbreak` option will affect the actual value of the title length. An easy fix can be `setlocal nowrap` for TelescopePrompt buffer. Or some other suggestions? Thank you!

<details><summary>Reproduce</summary>

1. nvim -nu test.vim
2. Open live grep search something that results in a long filename
3. Check the previewer title
</details>

<details><summary>Environment</summary>

- nvim --version output: NVIM v0.6.0-dev+119-g68f61b167
- Operating system: ArchLinux
- Telescope commit: 2c573b9

</details>

<details><summary>Configuration</summary>
<p>

```viml
set nocompatible hidden laststatus=2
set showbreak =╰─▸\ 

if !filereadable('/tmp/plug.vim')
  silent !curl --insecure -fLo /tmp/plug.vim
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

source /tmp/plug.vim
call plug#begin('/tmp/plugged')
Plug 'nvim-lua/popup.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
call plug#end()

autocmd VimEnter * PlugClean! | PlugUpdate --sync | close
lua require('telescope').setup({
  defaults = {
    dynamic_preview_title = true,
  }
})
```

**Comment by l-kershaw** [comment]
I can't reproduce this.
Can you give a file structure that consistently reproduces this problem?

---

Pictures below:
![long_folder_01](https://user-images.githubusercontent.com/35707277/128869526-4372a6a2-60ca-4041-83d6-3776c4911962.png)
![long_folder_02](https://user-images.githubusercontent.com/35707277/128869529-30a6b67d-ce88-40a9-854c-6315b577ea75.png)

**Comment by againxx** [comment]
Thanks for your quick reply!
Have you set `showbreak` to some non-empty string? And both set `wrap` to true?
![2021-08-10_22-11](https://user-images.githubusercontent.com/22728604/128882409-1f28d83c-e59c-4b9a-af67-db921c9cdf58.png)
![image](https://user-images.githubusercontent.com/22728604/128882507-24884bf2-3363-4289-af80-3979dfe091fe.png)
![image](https://user-images.githubusercontent.com/22728604/128882887-409a3732-5a7f-4879-b6ce-e126094fb4d0.png)
I think the key point may be `strdisplaywidth()` will take `showbreak` width into account, when I have a long wraped long with extra break characters.

**Comment by againxx** [comment]
I used nvim-dap to play aroud a little bit, and in `plenary.window.border`. When we update title, the computed title length was 90 for my contrived filename.
![image](https://user-images.githubusercontent.com/22728604/128883951-0f6cf617-4297-41a7-b2ae-61220d2ad326.png)

But was 86 in a normal full screen window. I think the **4** more characters may come from my `showbreak` setting.
![image](https://user-images.githubusercontent.com/22728604/128884163-5f1852c0-4a6e-44dd-a8b3-a11412ab75c3.png)
![image](https://user-images.githubusercontent.com/22728604/128884215-13ecd901-a5c9-43f6-b8a6-083f76f8ed92.png)

**Comment by l-kershaw** [comment]
Ah, I can now reproduce this. You're right, it seems to depend on the width of the prompt buffer.
I don't know if `setlocal nowrap` is the best solution, but I'll have a think about it.

**Comment by l-kershaw** [comment]
Apologies for the delayed response on this.

---

The first thing that I will note is that this issue is now more likely to come up, as some users may make their results windows thinner due to the new `truncate` option for `path_display`. This has the knock on effect of making prompt buffers smaller in a lot of layouts.

Secondly, this is more an issue with the titles implementation for `plenary` borders, than our specific use-case in Telescope.

---

I think there are two main ways of dealing with this issue:
- use `setlocal nowrap` in Telescope prompt buffers.
- temporarily change one of the relevant settings (`wrap` or `showbreak`) for when `strdisplaywidth` is called.

I'm not sure which one is best:
- I can't see a practical downside to using `setlocal nowrap` in the prompt buffer, but it feels weird to change a buffer setting for this issue
- this makes the code harder to follow, and there is also the decision of whether to include this adjustment in `strings.strdisplaywidth` or to just wrap this adjustment around it every time it is needed.

@Conni2461 what are your thoughts on this?
