### ISSUE TITLE
Show path endings in file previewer

### ISSUE THREAD

**Issue by minhduc0711** [nvim-telescope/telescope.nvim#1167]
**Is your feature request related to a problem? Please describe.**
Some of my paths are too long and I want to see the actual filenames, but I don't want to use `path_display= "shorten"`.

**Describe the solution you'd like**
An option to display the paths from their endings.

**Additional context**
By default, the paths are "left-aligned". I want them to be "right-aligned" instead.
![image](https://user-images.githubusercontent.com/34294427/130900628-f4d96e38-fef7-4492-961d-04f09bab2ed8.png)

**Comment by Conni2461** [comment]
we have `help telescope.defaults.dynamic_preview_title` but that is also doesnt truncate on the left side so i dont think it will help you for java.

Should be fairly easy to extend `dynamic_preview_title` but our strings library doesnt support truncate on the left side. https://github.com/nvim-lua/plenary.nvim/blob/master/lua/plenary/strings.lua#L95-L116

So this would be a double PR to plenary and telescope. PRs welcome

**Comment by minhduc0711** [comment]
But `dynamic_preview_title` only changes the previewer's title. I prefer the paths to be left truncated in the "Results" window as well, is it possible to add a new `path_display` option for this?

**Comment by joeycozza** [comment]
I know this is NOT a perfect solution, but until someone smarter than me can implement a solution that takes into account the view width, you can use something like this. This works for me because I almost always have the same sized width. So you could just tweak that maxLength variable to whatever you want and this will cut off the start of the strings that are too long and add "..." to them.

```lua
 path_display = function (opts, path)
      local pathLength = string.len(path)
      local maxLength = 41
      if pathLength > maxLength then
        path = '...'..string.sub(path, pathLength - maxLength - 3)
      end
      return path
    end,
```
![Screen Shot 2021-09-16 at 3 29 33 PM](https://user-images.githubusercontent.com/3885959/133688379-174d8b3e-3734-4a14-a1bd-083d65c59184.png)

**Comment by l-kershaw** [comment]
@minhduc0711 I am closing this, as there is now a `truncate` option for `path_display` (see `:h telescope.defaults.path_display` for more details)
If this doesn't fix your issue, feel free to reopen 🙂
