### ISSUE TITLE
live_grep history needed

### ISSUE THREAD

**Issue by menash134** [nvim-telescope/telescope.nvim#1181]
Everytime I open the live_grep, I need to type completely new for my search. It would be really cool to choose the string from my history of searches.  Thanks

**Comment by Conni2461** [comment]
We already have a pretty history, which is enabled by default but no are bound because we couldn't agree on good defaults. You can even replace the underlying implementation with something we called [smart-history](https://github.com/nvim-telescope/telescope-smart-history.nvim) a context sensitive history.

See `:help telescope.defaults.history` for all information

**Comment by menash134** [comment]
Hi Conni, Thanks for the information. It really helped.
