### ISSUE TITLE
colorscheme picker: Option to only include colorschemes from plugins.

### ISSUE THREAD

**Issue by quantum-booty** [nvim-telescope/telescope.nvim#1233]
I don't want any default colorschemes.

**Comment by l-kershaw** [comment]
I'm not sure how this would be implemented; is there a robust way to tell if a colorscheme is a default one? Filtering out the default names wouldn't work in all cases as some users may add in colorschemes with the same name via plugins.

Since this seems like a pretty specific feature to your workflow, I don't think this is something that the telescope core team would work on.

Closing as a `wontfix`, but if you want to write a PR to implement this, then I'm happy to review it (just ping me 🙂).
