### ISSUE TITLE
File picker that respects the `path` option

### ISSUE THREAD

**Issue by samhh** [nvim-telescope/telescope.nvim#1261]
I have a workflow that's oriented around (n)vim's `path` option. For greater interoperability I'd like a Telescope file picker that makes use of it under the hood.

I _think_ based upon some searching that this doesn't yet exist. Is it even possible?

Cheers!

**Comment by fdschmidt93** [comment]
I think the `search_dirs` flag could be used for that, eg 

```lua
require "telescope.builtin".find_files { search_dirs = {"../", "./", ....} }
```

see `:h builtin.find_files`

where `search_dirs` can be passed the folder in path (I think via `vim.opt.path:get()`, see `:h vim.opt`). Let me know if that works, otherwise happy to help.

I'll close this as I feel a dedicated picker for something like this is out of scope of telescope (if another member feels differently, feel free to reopen and tackle this).

**Comment by samhh** [comment]
Thanks for your reply!

I'm not having any luck with this: `:lua require 'telescope.builtin'.find_files { search_dirs = vim.opt.path:get() }`. As a sanity check replacing the last bit with `{ '.' }` works as you'd expect.

The trouble is that I think the formats are different. Here's my `:set path`: `path=,,,app/**,client/**,server/**,shared/**`

**Comment by samhh** [comment]
For anyone that finds this and wants the same functionality, here's a working example: https://github.com/samhh/dotfiles/commit/86bf3481b7d2ec5c44ef5fc46b726c143bf4b0af#diff-221816585e44f30a68fa70c4f81dc30ff9a5fc54d57b90572c90547b0712d028R29

It's a little rough around the edges but works well enough for my use case as described.
