### ISSUE TITLE
picker buffers sort_mru does not work as expected

### ISSUE THREAD

**Issue by bartpeeters** [nvim-telescope/telescope.nvim#1300]
### Description

Telescope pickers->buffers->sort_mru does not work as I would expect it to work.

The vim builtin `vim.fn.getbufinfo`, used by sort_mru, returns a list of all the buffers, with a lastused timestamp, but it does not return the values I would expect. I also wasn't able to find how lastused actually gets set.

Maybe my expectation is not what other people expect?

I created a [commit](https://github.com/bartpeeters/telescope.nvim/commit/408a4698e03b7cbf4021451f9944cfcdbdbdd897) as to how I would want it to work. It's my first time writing Lua so it is badly written.

### Neovim version

```
NVIM v0.6.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-AYHsFE/neovim-0.6.0~ubuntu1+git202110021200-724ffe709-adeb5640f=. -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim-AYHsFE/neovim-0.6.0~ubuntu1+git202110021200-724ffe709-adeb5640f/build/config -I/build/neovim-AYHsFE/neovim-0.6.0~ubuntu1+git202110021200-724ffe709-adeb5640f/src -I/build/neovim-AYHsFE/neovim-0.6.0~ubuntu1+git202110021200-724ffe709-adeb5640f/.deps/usr/include -I/usr/include -I/build/neovim-AYHsFE/neovim-0.6.0~ubuntu1+git202110021200-724ffe709-adeb5640f/build/src/nvim/auto -I/build/neovim-AYHsFE/neovim-0.6.0~ubuntu1+git202110021200-724ffe709-adeb5640f/build/include
Compiled by buildd@lcy01-amd64-011

Features: +acl +iconv +tui
```

Also have this on a Mac with neovim 0.5.

### Operating system and version

Ubuntu 20.04

### checkhealth telescope

```markdown
health#telescope#check
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 11.0.2
  - WARNING: fd: not found. Install [sharkdp/fd](https://github.com/sharkdp/fd) for extended capabilities

## ===== Installed extensions =====
```

### Steps to reproduce

Create a directory with files a, b, c and d.
Open neovim in this directory, use builtin.find_files to open a then b then c then d.
Use builtin.buffers to switch to file a.
Use builtin.buffers, now I would expect the buffers to be listed as:

- b
- c
- d

How they are actually listed:

- c
- b
- d

### Minimal config

```Lua
lua << EOF
local actions = require('telescope.actions')
-- Global remapping
------------------------------
require('telescope').setup{
  defaults = {
    mappings = {
      n = {
        ["q"] = actions.close
      },
    },
  },
  pickers = {
    buffers = {
      ignore_current_buffer = true,
      sort_mru = true,
      sort_lastused = true,
    },
  },
}
EOF
```

**Comment by Conni2461** [comment]
If i do open
- a
- b
- c
- d
- buffers -> a

then i expect `a` at the top (or if not ignored), then i expect `d` because its the buffer that was opened before `a` so the most recent one, then i expect `c`, because its the one we opened before `d` and then i expect `b`. Thats mru. Sort based on most recent used. Its NOT the order in which the buffers were created.

> The vim builtin vim.fn.getbufinfo, used by sort_mru, returns a list of all the buffers

partly true, it can also just return the information for the buffer handle passed it.

I think we support `mru` good enough. I dont know what you are missing here 
![image](https://user-images.githubusercontent.com/15233006/135729993-83e3dcac-c63f-4b0d-a320-2e23b957f247.png)

**Comment by bartpeeters** [comment]
https://user-images.githubusercontent.com/29534282/135730790-47ae5056-75c8-478f-84f1-97dc1856c08a.mov

I did select a and then buffers.

I expect the order when I do buffers after selecting a, to be

- b
- c
- d

But instead it's:

- c
- b
- d

Is this `mru`? `c` is still more recent than `b`.

**Comment by Conni2461** [comment]
I know why it behaving correctly for me and for you not. I have previewer disabled for buffers. So can you try and disabled previewer with `Telescope buffers previewer = false`. I think that should give you the correct behavior. Since a recent patch the previewer actually touches the buffer which should affect `getbufinfo`.

If this "solves" the issue than yes this is a bug and we need to address this. Thanks for reporting :) (of the top of my head i cant think of a fix that would actually work other than going back and "cloning" the buffer, like we did previously).

If this doesn't "solve" the issue than i have to save i cant reproduce your behavior sorry.

**Comment by bartpeeters** [comment]
Using `buffers previewer = false` did indeed "solve" the issue.
