### ISSUE TITLE
add caching mechanish for finder results

### ISSUE THREAD

**Issue by sunjon** [nvim-telescope/telescope.nvim#139]
I'm testing [Octo](https://github.com/pwntester/octo.nvim) which uses the GH API to gather a list of  issues/PRs.

Although it isn't of practical use for this plugin as it's currently designed, it's a good example of a source that takes several seconds to generate results and would benefit from caching.

I wrap results gathering block in the example from the plugins README with the following:

```lua
    local cache_timeout = 300 -- 5 min cache
    local results = {}

    local current_time = os.time()

    local next_check
    if vim.g.octo_last_updatetime ~= nil then
      next_check = vim.api.nvim_get_var('octo_last_updatetime') + cache_timeout
    else
      next_check = 0 -- now
    end

    if current_time > next_check then
      local resp = require'octo'.get_repo_issues(repo, {per_page = 50})
      print(resp.count)
      for _,i in ipairs(resp.issues) do
        table.insert(results, {
          number = i.number;
          title = i.title;
        })
      end
      vim.g.octo_last_results = results
      vim.api.nvim_set_var('octo_last_updatetime', current_time)
      print(string.format("results generated in %d seconds", os.time() - current_time))
    else
      results = vim.g.octo_last_results
    end
```

A native solution could make life easier.

**Comment by rockerBOO** [comment]
I believe there has been some desire to add caching support. @theprimeagen was working on a finder/sorter cache as well.

Also to consider, cache should work with threads to the degrees we want to index in a thread[s].

I think the notion of per nvim session and per telescope instance would be scope requirements. 

## Long term/refreshable cache
- Github Issues
- Github PR

### Ideas

Possibly use vim timers to act like garbage control. To clear out old caches (to implement a 5 minute cache).

## Sorters
- Sorter reducer cache (each prompt change reduces the finder results in a cache)
  - Cache helps to limit results to sort over by reducing the results into a cache. 

### Ideas 

Sorters want to cache across finder results but shouldn't directly know about previous sorting. 
Reducing finder results based on prompt into a cache can be tricky.

## Indexing (finders)
- Index finders into a cache in/from a thread
  - Because indexing can take some time, moving indexing to a thread can help performance. 

### Ideas

Using threads we have prototyped indexing into a thread. If we want to index into a cache (instead of a raw result list). This can be helpful to index PR's from Github and then cache the result set directly. Usage would be based on this cache which would be cleared by a timer callback. We can pre-populate this list or regularly update the cache list behind the scenes too. 

---

Maybe there is something we can make that will allow us to support these ideas but have a core idea of caching and clear/updating the cache.

**Comment by rockerBOO** [comment]
#52  May also be related as saving lists/caching lists have similar results.

**Comment by Conni2461** [comment]
Is this issue still relevant? We have caching for `finders.one_shot_job`. It takes all results and puts them in a table

**Comment by ghostbuster91** [comment]
@Conni2461 what about other types of jobs? I have a finder that for each prompt value does a new network call. 

I was trying to wrap it with some caching but as soon as I wrap the `async_finder` it stops working:
```lua

    local live_grepper = finders.new_job(function(prompt)  
       -- logic here 
    end
    local wrapper_finder = setmetatable({
        close = function()
            live_grepper:close()
        end,
    }, {
        __call = function(a, prompt, process_result, process_complete)
            live_grepper(a, prompt, process_result, process_complete)
        end,
    })
```
Closing the picker works, but nothing besides that.
