### ISSUE TITLE
Bug white typing in the telescope.nvim input

### ISSUE THREAD

**Issue by vzytoi** [nvim-telescope/telescope.nvim#1404]
### Description

Hi, firstly thanks for your interest into this issue.
Sometimes, when I launch telescope, and I start to write I get a bunch of messages on top of my vim. I linked a video so the issue can be more understable

### Neovim version

NVIM v0.6.0-dev+205-g9695691ee
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilé par runneradmin@fv-az152-120

Features: -acl +iconv +tui
See ":help feature-compile"

         fichier vimrc système : "$VIM\sysinit.vim"
               $VIM par défaut : "C:/Program Files/nvim/share/nvim"

Run :checkhealth for more info

### Operating system and version

Windows 10

### checkhealth telescope

```markdown
health#telescope#check
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - WARNING: nvim-treesitter not found. 

## Checking external dependencies
  - OK: rg: found ripgrep 12.1.1 (rev 7cb211378a)
  - OK: fd: found fd 8.2.1

## ===== Installed extensions =====

## Telescope Extension: `fzf`
  - INFO: No healthcheck provided
```

### Steps to reproduce

No specific step to reproduce

### Expected behavior

[2021-11-01 22-31-48.zip](https://github.com/nvim-telescope/telescope.nvim/files/7456331/2021-11-01.22-31-48.zip)

### Actual behavior

"

### Minimal config

```Lua
local actions = require('telescope.actions')

    require('telescope').setup {
        defaults = {
            file_ignore_patterns = {
                '.git/*'
            },
            prompt_prefix = '> ',
            vimgrep_arguments = {
                'rg',
                '--color=never',
                '--no-heading',
                '--with-filename',
                '--line-number',
                '--column',
                '--smart-case',
                '--hidden',
            },
            pickers = {
                find_files = {
                    find_command = { 'fd', '--type=file', '--hidden', '--smart-case' },
                }
            },
            mappings = {
                i = {
                    ['<c-k>'] = actions.move_selection_previous,
                    ['<c-j>'] = actions.move_selection_next
                },
                n = {
                    ['<Esc>'] = actions.close
                }
            }
        },
        extensions = {
            fzf = {
                fuzzy = true,
                override_generic_sorter = true,
                override_file_sorter = true,
                case_mode = "smart_case"
            }
        }
    }

    require('telescope').load_extension('fzf')
```

**Comment by Karanlos** [comment]
I'm facing similar issues shown in the video posted. For me it happens everytime a set of specific files are shown in the preview. All binary files cause this and some iOS project files cause this.

This happens in Command Prompt, Windows Terminal and Alacritty. Opening Neovim through WSL in Windows Terminal does not provoke this. If I try and use the same Neovim version in Windows by opening nvim-qt.exe it works perfectly fine. 
I've not experienced any other issues with Neovim other than opening Telescope and previewing a binary file.

I've tried with the only thing being imported is Telescope and Paq.

### Neovim version
NVIM v0.5.1
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 -DNVIM_TS_HAS_SET_MATCH_LIMIT /MD /Zi /O2 /Ob1 /DNDEBUG /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -ID:/a/neovim/neovim/build/config -ID:/a/neovim/neovim/src -ID:/a/neovim/neovim/nvim-deps/usr/include -ID:/a/neovim/neovim/build/src/nvim/auto -ID:/a/neovim/neovim/build/include
Compiled by runneradmin@fv-az152-633

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files/nvim/share/nvim"

Run :checkhealth for more info

### Operating System
Windows 11

### Steps to reproduce
Open Neovim in Windows Terminal, and preview a binary file.

### Expected Behaviour
"Binaries cannot be previewed" message is displayed

### Actual 
Bunch of nonsense is shown.
![image](https://user-images.githubusercontent.com/682628/139951797-f9daec5b-d8c2-45af-aeb9-2e3657511051.png)

### Minimal config 
```lua
local cmd = vim.cmd
local fn = vim.fn
local g = vim.g

cmd 'packadd paq-nvim'               -- load the package manager
local paq = require('paq-nvim').paq  -- a convenient alias
paq {'savq/paq-nvim', opt = true}    -- paq-nvim manages itself
paq {'nvim-telescope/telescope.nvim'}```

**Comment by fdschmidt93** [comment]
Same issue as https://github.com/nvim-telescope/telescope.nvim/issues/1263

> Opening Neovim through WSL

Because you have `file` there properly installed.

**Comment by fdschmidt93** [comment]
Ideally, you can test-drive #1413 on Windows and give feedback whether that branch fixes the issues with an out-of-the-box telescope configuration, as I unfortunately have no Neovim Windows setup.

Thanks in advance :)
