### ISSUE TITLE
Add path_display option for displaying paths relative to search_dirs

### ISSUE THREAD

**Issue by melkster** [nvim-telescope/telescope.nvim#1621]
**Is your feature request related to a problem? Please describe.**

I'm using a mapping for finding files in only one specific directory using `find_files` with the `search_dirs` option. I would like to use a `path_display` option so that the path to each file is displayed relative to that directory.

**Describe the solution you'd like**

An option for `path_display` called for instance `search_dir` that displays each file's path relative to the directory in `search_dirs` in which it was found.

**Describe alternatives you've considered**

At first I set up my own function for doing this as displayed below, however I realised that I wanted to use it together with other `path_display` options like `"truncate"`, which seemed very difficult to do.

```lua
function _G.telescope_markdowns()
  require("telescope.builtin").find_files({
    search_dirs = { '$MARKDOWNS' },
    prompt_title = 'Markdowns',
    path_display = function(_, path)
      return path:gsub(vim.fn.expand('$MARKDOWNS'), '')
    end,
  })
end
```

**Comment by l-kershaw** [comment]
I think that trying to implement such a thing within telescopes `path_display` option handling is going to overcomplicate the already complicated system for this.
However, if you want to use some of the other `path_display` options like `"truncate"` and `"shorten"`, you can use 
```lua
require('telescope.utils').transform_path({path_display={...}}, path)
```
within your `path_display` function. This function is what is used internally to apply all of the options.

I hope this helps 🙂 

---

Since this won't be implemented within telescope will close this issue now.
