### ISSUE TITLE
allow non-full-width prompt in ivy theme

### ISSUE THREAD

**Issue by max397574** [nvim-telescope/telescope.nvim#1639]
If I use the ivy theme the prompt is always the full width:
![Screenshot 2021-12-29 at 14 40 04](https://user-images.githubusercontent.com/81827001/147668109-d3f48e36-cd0e-4717-b04c-425a0d37ba24.png)

I'd like to be able to use a non full width prompt like here:
![Screenshot_2021-12-29_at_14 19 02](https://user-images.githubusercontent.com/81827001/147668198-6fab053f-83f7-4d7a-8c1b-d78aaf4de651.png)

As far as I can tell there is currently no way to do this in the bottom_pane strategy. The prompt width is hardcoded with the border (https://github.com/nvim-telescope/telescope.nvim/blob/1d1da664eb6505c318d405eea3d633c451edc2d8/lua/telescope/pickers/layout_strategies.lua#L851)

I would rly like to help implement this but I need guidance.

**Comment by l-kershaw** [comment]
So you want something similar to the `horizontal` layout, but anchored to the bottom of the screen?

Does the `anchor` option for that layout solve this issue?

**Comment by max397574** [comment]
yes thank you

**Comment by max397574** [comment]
I tried that out now
Do you know if there is a way to get this all the way down so there is no line with code below it @l-kershaw ?
![Screenshot 2021-12-29 at 16 17 36](https://user-images.githubusercontent.com/81827001/147676767-caea05e9-90c4-442e-8a6b-1ead704b925c.png)

**Comment by l-kershaw** [comment]
This is not currently possible due to the way that `resolve_anchor_pos` is implemented.
This function always gives the adjustment for leaving a gap from the side of 1 column/line.
My reasoning for this gap was that it mostly looks fine with a border, and always looks better when there is no border.

However, I think someone else asked about this on the gitter, so maybe I made the wrong choice here.
I am open to changing the extending/changing default behaviour of `resolve_anchor_pos` to allow for this "no gap" behaviour, but would want more people's opinions before doing this.

**Comment by max397574** [comment]
> If you want to tweak a layout for you own personal use, then that is totally possible, as the layouts are just lua functions in a table, and can be overwritten easily.

I'm not sure how I'd do this
could I just

```lua
local layout_strategies=require"telescope.pickers.layout_strategies"

layout_strategies.bottom_pane=.... -- paste here the original one with some changes
```
and then it would be changed if I use
```lua
layout_strategy="bottom_pane"
```
somewhere else? I couldn't find docs with an example for this
@l-kershaw

**Comment by l-kershaw** [comment]
Yes that should work
It isn't documented as it is only for advanced users, and we don't provide support if you break something by doing this.
