### ISSUE TITLE
Add git tags for last supported version shas

### ISSUE THREAD

**Issue by ViViDboarder** [nvim-telescope/telescope.nvim#1664]
Neovim is in a rapid development cycle resulting in changes breaking support for 0.5.0 then 0.5.1, I expect this will happen when in the future. Additionally, the cycle is faster than many distros after bundling versions.

It would be useful to have the last supported sha for each no longer supported Neovim version as a tag to make pinning easier.

Eg. `nvim-0.5.0 = 587a10d1494d8ffa1229246228f0655db2f0a48a` and `nvim-0.5.1 = 80cdb00b221f69348afc4fb4b701f51eb8dd3120`

**Comment by Conni2461** [comment]
Yeah i already acknowledged on twitter that i should have done that. So done: https://github.com/nvim-telescope/telescope.nvim/tags

But we won't maintain a branch that is compatible with these neovim version because we don't have the team for that. Also you should always try to run at least the latest patch version, so right now you shouldn't be on 0.5.0

**Comment by ViViDboarder** [comment]
I hadn't seen any mention of it until now, but thanks for doing it! I'm running 0.6.0 on most of my machines, but I try to keep my config as flexible as possible.
