### ISSUE TITLE
Duplicates path entries on Windows

### ISSUE THREAD

**Issue by kishikaisei** [nvim-telescope/telescope.nvim#1683]
### Description

There is duplication of entries when we are talking of paths, as seen in the screenshot below:
![image](https://user-images.githubusercontent.com/1894123/149155383-4f7440df-c23f-4350-aa84-367bbae1f03b.png)

### Neovim version

```markdown
NVIM v0.7.0-dev+793-g991e872d8
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

### Operating system and version

Windows 11

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0 (rev af6b6c543b)
  - OK: fd: found fd 8.3.0

## ===== Installed extensions =====

## Telescope Extension: `projects`
  - INFO: No healthcheck provided
```

### Steps to reproduce

1. On windows, open a file a few times.
2. At some point it will duplicated in old_files, as there will be two path, one containing `\` the other having `\\`.

### Expected behavior

No duplication of paths, every folder/file have a single entry

### Actual behavior

Files and folders are sometimes duplicated due to having single or double forward slashes (as per screenshot in description)

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by Conni2461** [comment]
We only display what `vim.v.oldfiles` returns. The root problem of this was just fixed in plenary. that paths sometimes weren't normalized correctly (fixed in https://github.com/nvim-telescope/telescope.nvim/issues/1105#issuecomment-897150724). That means that oldfiles thinks `C:\Users\asdf\Desktop\notes.norg` and `C:\Users\asdf\\Desktop\notes.norg` are different files because of that `\\`.

I would close this because we just fixed it (at least on linux) i can't verify windows. So if you see this problem again, feel free to open a bug report over at plenary (because it has not really anything to do with duplicated path entries) :)

Note that `oldfiles` might still contain broken paths from before updating your plugins.
