### ISSUE TITLE
[Feature] Add an option to search for exact tag name only

### ISSUE THREAD

**Issue by pidgeon777** [nvim-telescope/telescope.nvim#1822]
Actually, when searching for a tag, the search occurs fuzzily in both path and tag names.

It would be nice to add an option so that the input text is used as a filter for exact matches of the tag name only.

This would be useful when looking for exact references of a tag under the cursor (could be read as input with <C-w>).

**Comment by Conni2461** [comment]
I wanna close this report so bad, because it misses so many things. It did not fill out our feature template. I do not know about which builtin you talk. So yeah. Closing

For your information you can do exact search using: https://github.com/nvim-telescope/telescope-fzf-native.nvim And if you talk about `Telescope tags` you can enable `only_sort_tags` option, ignoring the path. `help builtin.tags`.

(I flag this as "missing bug template" even thought its a features request)
