### ISSUE TITLE
Allow `ordinal` inside entry_maker to have a function value

### ISSUE THREAD

**Issue by max397574** [nvim-telescope/telescope.nvim#1830]
I just realized that `ordinal` can't take a function value as input.
This would be really useful if you change the `display` to something that isn't available in the entry table.

I think I could do this pr if nobody else does it.

**Comment by Conni2461** [comment]
making `ordinal` a function doesn't really make sense because we need to have all ordinals anyway to calculate a score. For display it does because then you can do fancy more expensive formatting and we only ever calculate it for the entries actually displayed. So if you have a million entries and telescope opens we calculate 1000 display (because of scrolling) and then you start typing till you find your value you are looking for and in that process maybe 2000 or so were ever rendered so we only ever calculate the display for these 2000.

But we always need an ordinal for every value because we need to match it. And then its an unnecessary overhead if we now have to check are you a function of are you a string. You can just write your own function and calculate it in the entry maker instead because that would have happend a few cycles anyway.

> This would be really useful if you change the display to something that isn't available in the entry table.

I dont get this reason

**Comment by max397574** [comment]
I just wrote a guide for an example picker (https://github.com/nvim-neorg/library-of-norgxandria/pull/2, should I convert this to markdown for this repository?)
And there the entries are in `snake_case`. To make them look nicer I replace the `_` with a space (no problem) and make the first character uppercase -> `Snake case`
But if then the user searches for `S` there will be no matches.
That `Snake case` is nowhere in the entry table so I can't use it as `ordinal` value.


And I think if you have a million entries just don't make ordinal a function.
So this is in my opinion no reason to not implement it.
Perhaps you could add a notice that this will be calculated for all entries and therefore could be heavy on performance.

**Comment by Conni2461** [comment]
In this case just make this
```lua
local function name_format(name)
  local res = name:gsub("_", " ")
  local res = res:sub(1,1):upper()
  -- whatever [2, -1] is, its not valid lua code
  return res..name[2, -1]
end

local make_entry = function(project)
  local format = make_format(project)
  return {
    value = project,
    display = format,
    ordinal = format,
  }
end

-- later
-- entry_maker = make_entry
```

This only creates 1 string reference and is the same for display and ordinal. If you have two functions you end up with two references one for display and one for ordinal.

And a pretty big reason against it is that we still have to resolve it similar to display which is a pretty big performance hit if you use it or not.

https://github.com/nvim-telescope/telescope.nvim/blob/8af0d384d21104be3cb055494aab9a6f86d94067/lua/telescope/pickers/entry_display.lua#L91-L107

**Comment by max397574** [comment]
Should I convert the norg file to markdown for this repository?

**Comment by Conni2461** [comment]
If you want. I always want more documentation :) 

But i am not 100% sure how you want to "convert" it. Just adding an additional markdown file to this repo, probably not. Adding additional information to the features not already described to the already written developers.md yes please!

**Comment by max397574** [comment]
I'd have to look at the developers.md again
But what I think I have that isn't there is custom preview and entry highlighting based on a function.

**Comment by Conni2461** [comment]
Closing this issue as wont fix. I presented my reason on why we wont want this feature.

About the docs. If you have something that works with our current documentation, just open a PR and i take a look at it thanks :)
