### ISSUE TITLE
checkout to a new branch when the typed string leads to no results

### ISSUE THREAD

**Issue by danielo515** [nvim-telescope/telescope.nvim#1852]
**Is your feature request related to a problem? Please describe.**
It will be very handy if the built in git branches allows you to create a new branch if your search string leads to no results

**Describe the solution you'd like**
Maybe an extra step asking for confirmation before creating the branch will be required

**Describe alternatives you've considered**
Right now, I have to close the window and create the branch myself

**Additional context**
This is something I got used to on VSCode

**Comment by Conni2461** [comment]
`:help telescope.builtin.git_branches()`

On default we can create new branches with `<C-a>`, just type in the name and press the keybinding.

Currently thinking maybe we can also generate the mappings we have on default :thinking: rather than having to make sure we update the docs and actually document all mappings. Should be fairly straight forward

**Comment by danielo515** [comment]
Does that keybindign appear when you ask for keybindings in the telescope window itself? I meant pressing `? ` in normal mode. I'm asking because I usually check the inline help and I don't remember seeing it

**Comment by Conni2461** [comment]
![image](https://user-images.githubusercontent.com/15233006/164325520-6019bee0-d2e8-4ce7-9ce0-6629098a846c.png)

apparently. nice @fdschmidt93

**Comment by Conni2461** [comment]
closing, i answered this question
