### ISSUE TITLE
git_bcommits should include the complete commit message in preview pane?

### ISSUE THREAD

**Issue by briandipalma** [nvim-telescope/telescope.nvim#1864]
**Is your feature request related to a problem? Please describe.**
I'm loving using git_bcommits to browse a file's history but it would be nice if I could get easy access to the entire commit message as there are often Jira IDs/issue IDs/further valuable information.

**Describe the solution you'd like**
I'm not sure if it's reasonable but maybe put the entire commit message at the top of the preview pane?

**Comment by fdschmidt93** [comment]
There's a few solutions here

** Cycle previewer to git message

`:Telescope git_bcommits` has cycle-able previewers, one of which shows the commit message.

You can map `require "telescope.actions".cycle_previewers_next` and `require "telescope.actions".cycle_previewers_previous` to keys to cycle through available previewers.

**Print message to cmdline**

Something like
```lua
local action_state = require "telescope.actions.state"

-- have as separate function to show in which_key
local show_full_msg = function(prompt_bufnr)
  local entry = action_state.get_selected_entry()
  -- for instance, print full line to cmdline
  print(entry.msg)
  -- or send notification
  vim.notify(entry.msg, vim.log.levels.INFO)
end

require "telescope".setup {
  pickers = {
    git_bcommits = {ignore_verifications
      ["YOUR_KEY"] = show_full_msg
    }
  }
}
```

I haven't tried this but something like this should work.

You probably also could modify the preview title to achieve what you want, but I think the provided solutions are satisfactory.

Closing this as `wontfix` since I don't think anyone of the team would make a PR to have this builtin (though I guess we'd accept one to make it default with `dynamic_title` eg).

If another team member feels differently, please reopen.

**Comment by briandipalma** [comment]
```lua
local telescope = require("telescope")
local actions = require("telescope.actions")

telescope.setup({
	defaults = {
		mappings = {
			i = {
				["<C-s>"] = actions.cycle_previewers_next,
				["<C-a>"] = actions.cycle_previewers_prev,
			},
		},
	},
})
```

Thanks, that works great. I don't understand why these bindings aren't default thought TBH. They really should be.
