### ISSUE TITLE
Sort Results top/down

### ISSUE THREAD

**Issue by joshmedeski** [nvim-telescope/telescope.nvim#1933]
**Is your feature request related to a problem? Please describe.**
When I place the prompt at the top, the results end up being too far away from the text I type.

<img width="1917" alt="Screen Shot 2022-05-10 at 4 30 24 PM" src="https://user-images.githubusercontent.com/2036594/167725677-036a8be7-dcfa-4d21-b797-0deb0a7af118.png">

**Describe the solution you'd like**
I would like to be able to sort the results from the top to the bottom (opposite of the default behavior)

**Describe alternatives you've considered**
I read the docs and couldn't figure out how to get it working.

**Additional context**
I prefer things being on the top of the screen, not the bottom. So I'd like to move the prompt and results up at eye level.

**Comment by joshmedeski** [comment]
Okay, after reviewing the docs I see I can use the following configuration

```lua
local telescope = require('telescope')

telescope.setup {
  defaults = {
    sorting_strategy = "ascending",
    layout_config = {
      prompt_position = "top"
    }
  }
}
```

Hope this helps someone else!

**Comment by mahume** [comment]
I've noticed an issue when changing sorting_strategy between ascending and descending with prompt_position set to top.

```
opts = {
    defaults = {
        prompt_prefix = '❯ ',
        sorting_strategy = 'ascending',
        results_title = false,
        layout_config = {
            horizontal = {
                prompt_position = 'top',
                width = { padding = 0 },
                height = { padding = 0 },
                preview_width = 0.6,
            },
        },
    },
}
```

Desired behavior:
Search file name. Total of 100 file paths. 10 paths fuzzy match. 10 matches shown in results.

Actual behavior:
Search file name. Total of 100 files paths. 10 paths fuzzy matches. 1 matching row shows in results. 

The behavior works as expected when changing sorting_strategy to descending when prompt_position is set to top. However the actual (undesired) behavior happens when sorting_strategy is set to ascending with prompt_position remaining set to top.

**Comment by jamestrew** [comment]
@mahume If you're on neovim 0.10+, you might just need to update telescope.
If you're sure you're on at least telescope 0.1.7+ and still experiencing this, please open a new bug report with more details.
