### ISSUE TITLE
Is there any function to replace all the search results？

### ISSUE THREAD

**Issue by 505384662** [nvim-telescope/telescope.nvim#1941]
![image](https://user-images.githubusercontent.com/31720616/168941721-5aaae13d-b9b0-45f9-9074-482409aa4ba3.png)

For example, Will be replaced with "skynet.socket" to "socket"

**Comment by fdschmidt93** [comment]
There is no such functionality directly embedded into telescope nor are there plans to do so since the canonical (neo)vim way is to do this via the quick fix list. You'd sent your results there (`<C-q>`) and then lever the quickfix list. See also my first link.

https://github.com/nvim-lua/wishlist/issues/18#issuecomment-812092951 

or an alternative to this would be

https://github.com/nvim-pack/nvim-spectre

**Comment by 505384662** [comment]
I’m truly grateful for your help.
