### ISSUE TITLE
Ability to display tree-like structures

### ISSUE THREAD

**Issue by danielo515** [nvim-telescope/telescope.nvim#1993]
**Is your feature request related to a problem? Please describe.**
I was wondering if it would be possible for a picker to show tree structures in place of a list. I'm not saying this has to be added to the built-in pickers (although I think it will be look cool in the file one), but will be nice to have some primitives to allow building on them. Everything should behave the same, this is just a visual thing.

**Describe the solution you'd like**
Some way to display tree structures within the picker list, with the ability to filter it

**Describe alternatives you've considered**
Using a different plugin, like neo-tree but adding the previewing capabilities of telescope, if they can be used outside of a picker

**Additional context**
I really like using telescope for buffer and file navigation, but having the entire file path on every entry makes it a bit noisy and usually not the entire path fits inside.

**Comment by fdschmidt93** [comment]
There's two options.

>  I really like using telescope for buffer and file navigation, but having the entire file path on every entry makes it a bit noisy and usually not the entire path fits inside.

The simple one is manipulating `path_display`, see `:h telescope.defaults.path_display`, though I'll be honest a tree-structure probably makes this even longer.

You are free to write your own [entry_maker](https://github.com/nvim-telescope/telescope.nvim/blob/e6b69b1488c598ff7b461c4d9cecad57ef708f9b/lua/telescope/make_entry.lua#L61-L134) and pass it to `builtin.find_files`. 

You can get started by having a look at [developers.md](https://github.com/nvim-telescope/telescope.nvim/blob/master/developers.md).

I'm closing this as `wontfix`, since this with extremely high likelihood is not something we will provide from `telescope.nvim` itself, as this is a very user-specific feature with very high maintenance burden, for starters (plus lots of other considerations as to why that's practically not feasible to support for us). There's enough flexibility s.t. you can implement this yourself and possibly make it available as an extension.

**Comment by danielo515** [comment]
Hey, totally understandable. 
My question was more about if it is possible to do it with the current API (to write such entry maker) and enhance it if not. So I guess it is doable, right?
I'll take a look at writing my own entry maker.
