### ISSUE TITLE
How to inject mappings to builtin telescope function

### ISSUE THREAD

**Issue by tami5** [nvim-telescope/telescope.nvim#203]
Hey there, I have the following function that I want to map to a a custom function I'm creating on the top of builtin find_files:

```lua

local tmux-_open = function(prompt_bufnr)
  local actions = require'telescope.actions'
  local entry = actions.get_selected_entry(prompt_bufnr)
  actions.close(prompt_bufnr)
  local cmd = string.format("!tmux new-window nvim %s", entry.value)
  vim.cmd(cmd)
end
```

I tried the following:

```lua

require'telescope.builtin'.fd({
   defaults = { mappings = {i = {["<CR>"] = tmux_open}}}}
})

require'telescope.builtin'.fd({
  mappings = {i = {["<CR>"] = tmux_open}}}
})

require'telescope.builtin'.fd({
  attach_mappings = {["<CR>"] = tmux_open}
})

```

None of the above worked. Thanks

**Comment by tjdevries** [comment]
You'll want to do something like this:

```lua
require'telescope.builtin'.fd({
  attach_mappings = function(prompt_bufnr, map)
    map('i', '<CR>', tmux_open)
  end
})

```

**Comment by tjdevries** [comment]
Does the commit: 37c4f1b help with documentation?

**Comment by tami5** [comment]
It does, thanks a lot @tjdevries I will try it out.

**Comment by runiq** [comment]
The docs in https://github.com/nvim-lua/telescope.nvim/commit/37c4f1b355d843e95ba41f2a73d83de58fb74dae say that I can use `attach_mappings` in the setup table, so I'd expect it to work for builtins as well. But then the docs go on to use `attach_mappings` in a custom `picker.new()` instead. Using `attach_mappings` in `setup()` doesn't appear to work right now, because each builtin picker appears to have its own version of `attach_mappings()` or something?

I'm not sure, sorry, this is too many layers for me :sweat_smile:

**Comment by tami5** [comment]
#216
