### ISSUE TITLE
insert mode ctrl-o then try telescope command

### ISSUE THREAD

**Issue by Josiah-tan** [nvim-telescope/telescope.nvim#2052]
### Description

hi I really enjoy using this plugin. If possible please find a way to fix this bug.

make any mapping to evoke telescope floating window (something like leader ff to find files)
go to insert mode
then try ctrl-o
then use the mapping you made earlier to evoke telescope floating window
then in the fuzzy finder there will be an "A" in the beginning of the prompt

### Neovim version

```markdown
NVIM v0.8.0-dev
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

ubuntu 22.04

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - OK: fd: found fd 8.3.1

## ===== Installed extensions =====

## Telescope Extension: `git_worktree`
  - INFO: No healthcheck provided

## Telescope Extension: `neoclip`
  - INFO: No healthcheck provided

## Telescope Extension: `notify`
  - INFO: No healthcheck provided

## Telescope Extension: `refactoring`
  - INFO: No healthcheck provided
```

### Steps to reproduce

let me know if necessary

### Expected behavior

there shouldn't be an "A" in the start of the prompt

### Actual behavior

![image](https://user-images.githubusercontent.com/65082231/178004144-32819aba-9874-49a9-9dd7-d9c4127ee713.png)

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by Josiah-tan** [comment]
I think the bug is about the same, however the trigger for the bug is slightly different in that I actually press the "control-o" on my keyboard before invoking the normal mode mapping space ff.

**Comment by Josiah-tan** [comment]
it would be nice if there was a way to be in insert mode, press control-o, then do whatever normal mode mapping does, press enter to perform an action of some sort, then go back to insert mode automatically.
 but if that is not possible, then I guess I can just escape first before activating telescope, but it wouldn't have the benefit of being able to instantly return back to insert mode afterwards

**Comment by fdschmidt93** [comment]
> it would be nice if there was a way to be in insert mode, press control-o, then do whatever normal mode mapping does, then press enter to perform an action of some sort, then go back to insert mode automatically.

Pretty sure it's not. You're of course free to get a solution working, but unfortunately that logic within telescope is extremely sensitive and took a few iterations to arrive at the solution we have that seems to work well for anything but ctrl-o from insert mode as explained above/other issue. I won't touch that code for this use case, because

> but if that is not possible, then I guess I can just escape first before activating telescope, but it wouldn't have the benefit of being able to instantly return back to insert mode afterwards (assuming that I only ever create normal mode mappings)

workarounds are there, like starting telescope from insert mode or leaving into insert mode (see [here](https://github.com/nvim-telescope/telescope.nvim/blob/10a3310546284faae4ada397a61d68e0a8d0d9f7/lua/telescope/actions/init.lua#L458-L465))

> but it wouldn't have the benefit of being able to instantly return back to insert mode afterwards 

From what I gather I think you are assuming "insert mode" > telescope > "return to original insert mode". ctrl o would not be able to work like that because of the async nature of a telescope picker. It would have long tried to go back into insert mode before you've finished with telescope, which is why you see the `A`. 

Anyways, closing as `wontfix` (from telescope maintainers side, you are free to make a PR) since I believe it's not possible or worth the material effort.

**Comment by Josiah-tan** [comment]
I see thanks for letting me know!
