### ISSUE TITLE
find_files with symbol or line number

### ISSUE THREAD

**Issue by huuson235** [nvim-telescope/telescope.nvim#2062]
Do we have any plugins that help us find files with symbols (like @ in sublime) or the line number (like : in sublime)?
Thanks.

**Comment by fdschmidt93** [comment]
Here's code snippets that may or may not work (quite dated) but show you how you might be able to go about this.

https://github.com/nvim-telescope/telescope.nvim/issues/1042

You'd be very welcome to turn this into an extension.

I'm closing this as `wontfix` since this is probably not something we'd have in telescope-core per se but could maybe be added to the Wiki instead (again, very welcome if you come up with a working snippet).
