### ISSUE TITLE
:Tags command similar to Fzf

### ISSUE THREAD

**Issue by yujinyuz** [nvim-telescope/telescope.nvim#209]
Is it possible to achieve something like the `:Tags` command similar to what FZF does?

It just basically displays what's inside of my `tags` file.

[![asciicast](https://asciinema.org/a/FzTjMFeg7pmvdmW6jCJEPtVko.svg)](https://asciinema.org/a/FzTjMFeg7pmvdmW6jCJEPtVko)

**Comment by Conni2461** [comment]
Hey thanks for reporting this. I have a WIP version in #219.
Could you try it out. It does not work very well. e.g. Jump does not work and you might have to generate the `tags` file with `ctags -R --fields=n`. You can see the whole lists of tasks i have to do in the PR.

**Comment by macintacos** [comment]
Just wanted to post my solution for getting tags + Telescope to auto-update so that I didn't have to run `ctags -R` manually anytime I made significant changes in a project:

- [Installed the latest ctags](https://github.com/universal-ctags/ctags#the-latest-build-and-package)
- Installed https://github.com/ludovicchabant/vim-gutentags
- Found [this issue](https://github.com/ludovicchabant/vim-gutentags/issues/161) which allowed me to ignore files specified in .gitignore for a given project (optional, but probably desired so you can ignore cruft)

Seems to be working like a charm for me. Hope that helps someone in the future - I was doing a bit of digging around because I didn't want to use some other tool to get this functionality. If there are any cleaner solutions, I'm all ears :)
