### ISSUE TITLE
Is there a method to ignore spaces in input

### ISSUE THREAD

**Issue by Josiah-tan** [nvim-telescope/telescope.nvim#2102]
**Is your feature request related to a problem? Please describe.**
It would be nice if there was way to allow telescope to remove spaces when inputting text

**Describe the solution you'd like**
have some sort of preprocessing function (that can remove the spaces) that I can pass through the defaults.

**Describe alternatives you've considered**

**Additional context**
current behaviour:
`sandbox py` would not match `sandbox.py`
new behaviour:
`sandbox py` => `sandboxpy` => fuzzy matches with `sandbox.py`

**Comment by Conni2461** [comment]
our default fuzzy find algo is fzy (because its easy and someone spend the time porting it to lua). This algo does not support this feature

I on the other hand spend the time porting fzf algorithm with its search syntax to c for telescope. It has support for space

https://github.com/nvim-telescope/telescope-fzf-native.nvim

**Comment by Josiah-tan** [comment]
Thank you very much this is great!
