### ISSUE TITLE
Show dot files results using find_files while respecting .gitignore

### ISSUE THREAD

**Issue by ziontee113** [nvim-telescope/telescope.nvim#2105]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I use `Telescope find_files` in my dotfiles folder, which has files like `.zshrc` or `.tmux.conf`. They are hidden by default in Telescope.

I know about customizing the `find_files` picker with the `hidden = true` option, but it also shows everything including files in the `.git` folder, which pollutes the search results.

**Describe the solution you'd like**
An option to show everything except `.git` folder and everything in `.gitignore` file.

**Comment by ziontee113** [comment]
The current solution I can find is 
```lua
	pickers = {
		find_files = {
			find_command = { "rg", "--files", "--hidden", "-g", "!.git" },
		},
	},
```

**Comment by Conni2461** [comment]
`builtin.files` is a frontend for `fd`, `rg`, ... so we follow these options with our shorthand options. The solution you found is the correct solution, we should not add additional ignore dirs/files on the hidden shorthand as this would be intuitive

**Comment by avegancafe** [comment]
sorry for the posthumous comment, but I figured since `fd` is a more recommended file searcher I'd list its use case here as well. This is what I use to accomplish the same thing with `fd`:

```
pickers = {
  find_files = {
    find_command = { "fd", "--hidden", "--glob", "" },
  },
}
```

 and in addition to this, if you want to not include `.git` files in your results as well, you can create a `.fdignore` file in your home directory as I did here: https://github.com/avegancafe/Juliet/commit/a6bb05d312f7af53547ddbc377ac8c5b29d56e33
