### ISSUE TITLE
Add a search option to current_buffer_fuzzy_find

### ISSUE THREAD

**Issue by thezealousfool** [nvim-telescope/telescope.nvim#2114]
New to telescope. Thank you for the plugin.

I was creating some keymaps for visual mode selected text search. `telescope.builtin.grep_string` lets me pass a `search` option so I can search for the selected text in the cwd. Can we have a similar option for `current_buffer_fuzzy_find` so that we can search the selected text in the current buffer.

Thank you.

**Comment by fdschmidt93** [comment]
Any picker accepts a `default_text` parameter, that is

```lua
require "telescope.builtin".current_buffer_fuzzy_find { default_text = $YOUR_TEXT }
```

will set the prompt buffer with `$YOUR_TEXT` which you can populate with your visual selection search. This will eventually be documented as part of #1954.

Closing as I'm very optimistic this addresses your issue. Kindly let me know otherwise.
