### ISSUE TITLE
respect .gitignore without git repository

### ISSUE THREAD

**Issue by williamhCode** [nvim-telescope/telescope.nvim#2152]
When I create, say a gradle project, and .gitignore files get generated automatically to ignore the .gradle and build files, telescope will still search for those files. It seems like if I don't initialize the directory with git init, then telescope does not respect .gitignore. This is really frustrating because if I'm just doing small projects of assignments locally, I have create a local git repo.

It would be nice if find_files respects .gitignore even if the directory is not a git repo.

**Comment by Conni2461** [comment]
We only provide a frontend for other tools, like `ripgrep`, `fd` and `git`. So `Telescope git_files` will not help if you have no repo initialized.

`find_files` uses either `ripgrep` (prio 1) or `fd` (prio 2) depending on installed tools on your system. We do not parse gitignore and we will never do that because its kinda hard with `!` and nested gitignores ... So both `ripgrep` and `fd` handle ignoring so this is also the behavior if you execute these commands on cli.

Either go to the respected tool and do that feature request there, i do not know if they want this or if this was already requested, so please do your research before opening a new issue.

You can also do `rg --files --ignore-file .gitignore` or `fd --ignore-file .gitignore` and this works without a `.git`

So `:help telescope.builtin.find_files()` shows a `find_command` option. So you could do

```lua
local my_find_files = function(opts)
  -- we only want to do it if we have a gitignore and no .git dir
  if vim.fn.filereadable(".gitignore") == 1 and vim.fn.isdirectory(".git/") == 0 then
    opts.find_command = { "rg", "--files", "--ignore-file", ".gitignore" }
  end
  require("telescope.builtin").find_files(opts)
end
```
and then map the function with vim.keymap. (its untested because written in github right now but pretty sure it should work)

So yeah i dont think we(telescope) shoud do anything here

**Comment by williamhCode** [comment]
Makes sense, thanks for the reply!

I can confirm this works, and I also added a line to make opts optional.
```lua
local my_find_files = function(opts)
    opts = opts or {}
  -- we only want to do it if we have a gitignore and no .git dir
  if vim.fn.filereadable(".gitignore") == 1 and vim.fn.isdirectory(".git/") == 0 then
    opts.find_command = { "rg", "--files", "--ignore-file", ".gitignore" }
  end
  require("telescope.builtin").find_files(opts)
end
```
