### ISSUE TITLE
Feat: Scroll left/right in previewer

### ISSUE THREAD

**Issue by martin-braun** [nvim-telescope/telescope.nvim#2243]
**Is your feature request related to a problem? Please describe.**
I have to work with a lot of code, that I didn't write and I choose to disable word-wrap and prefer to horizontally scroll with `zH` and `zL` when necessary. In my work, I often have to deal with code that is too long, horizontally.
Unfortunately, on grep search the preview window can only be scrolled up and down, but not left and right, so I have problems to preview such files.

**Describe the solution you'd like**
Keybindings to scroll left or right or forced word-wrap. The former is preferred.

**Describe alternatives you've considered**
I'm aware that I can send the results to a quick fix window using `<C-q>`, but it is less ideal for me.

**Comment by l-kershaw** [comment]
I think that left/right scrolling could be (partially) implemented by sending `zL` and `zH` to the preview buffer (this is similar to how vertical scrolling is implemented).
However, you would run into issues when you have a mixture of very long and very short lines in the file you are previewing.

In a normal buffer (outside `telescope`) using `zL` `zH` (and variants) while your cursor is on a short line, you won't move at all horizontally.
Since the cursor is not shown in the `telescope` preview buffer, this is likely to cause confusion.

I can't think of another way to implement horizontal scrolling that avoids this problem 😕

**Comment by martin-braun** [comment]
dup #2211
