### ISSUE TITLE
Documentation Incompleteness

### ISSUE THREAD

**Issue by royfeldt** [nvim-telescope/telescope.nvim#2521]
### Description

# Pickers

https://github.com/nvim-telescope/telescope.nvim#pickers

You need to _define_ what a picker is. Apparently it is some thing that takes a list of items, accepts a choice and then responds? 

Then,

# Extensions

What are extensions? They can be pickers, or previewers, or sorters, what?

### Neovim version

```markdown
This is not applicable.
```

### Operating system and version

13.3.1

### Telescope version / branch / rev

v0.1.1

### checkhealth telescope

```markdown
This is not applicable.
```

### Steps to reproduce

The steps to reproduce are to make documentation complete and understandable and with aria in mind.

### Actual behavior

The actual behaviour is that the documentation is abysmally incomplete.

### Minimal config

```Lua
There is nothing to write here because it has nothing to do with configuration.
```

**Comment by jamestrew** [comment]
>  is abysmally incomplete

That's a bit harsh. This is a community maintained project. Contributions are always welcome.


If you are interested in learning more about pickers and maybe making your own telescope extension, you can find more info under the [developers documentation](https://github.com/nvim-telescope/telescope.nvim/blob/master/developers.md).

**Comment by royfeldt** [comment]
I didn't mean to be harsh dude.

The truth hurts.

**Comment by royfeldt** [comment]
I am reopening this because there are zombies in enormous numbers not consenting to fixing an obvious problem with the documentation.

**Comment by Conni2461** [comment]
yeah great job insulting the countless hours spend by contributors and maintainers not just writing a free plugins but also taking the time to document a lot of the functionality and configuration, in `:help telescope`, the readme that acts as getting started and the developer documentation that acts as an tutorial to get you up and running with your own custom functionality.

Nobody says its perfect but its better than you make it out to be.

> The actual behaviour is that the documentation is abysmally incomplete

This issue is not actionable and is just unnecessary noise, insults the hard working contributors.

And no the truth doesn't hurt! I'm prod of every single contributors work!

Please find another hobby!
