### ISSUE TITLE
Wishlist

### ISSUE THREAD

**Issue by tami5** [nvim-telescope/telescope.nvim#255]
Here we can post ideas of *features*, *improvement* and *new pickers*. 

Later we can further refine an idea and update progress on it or link it  to a more detailed "enhancement/feature issue", or even reference the comment in a PR.

Try to leave discussions out of here, but if necessary or your have something in mind post it then mark your replies and mentions as out of scope to keep the Wishlist clean.

**Comment by tami5** [comment]
Feature: combine pickers #213 . I agree with @wbthomason , I think its really useful in cases where you want to combine things like 

- quickfix + loclist 
- old_files + buffers
- dotfiles + nvim + bin files ...

**Comment by tami5** [comment]
Enhancement: add additional parameter to determine the depth of a given cwd #176 . Useful when you want to set the cwd but you don't want to go further than 2 levels

**Comment by tami5** [comment]
Feature: Create a picker for [vista](https://github.com/liuchengxu/vista.vim). First suggested by tj in #138

**Comment by tami5** [comment]
Idea: with `actions._goto_file_selection(prompt_bufnr, command)` if no entry, instead of `print("[telescope] Nothing currently selected")` edit any way, sometime I'd like to create a file if it doesn't exists.

**Comment by tjdevries** [comment]
documentation generator :)

**Comment by tamago324** [comment]
builtin add 'filetypes'

**Comment by tami5** [comment]
> documentation generator :)

I can work on this @tjdevries  using https://stevedonovan.github.io/ldoc/  it may take few weeks to go over the code base but I will be happy to do it. Later we can use the output from ldoc, manipulate it and create doc/telescope.txt or even webpage :D

**Comment by sharksforarms** [comment]
builtin for `:highlights` :)

**Comment by sunjon** [comment]
A lot of the ideas here  are relocated(prioritized?) existing issues.

The ability to scroll through the search results is a frequent pain for me. I don't think fuzzy finders are intended to filter results down to 5-10 items;  Often the choice is offscreen due to sorting, and knowing it exists momentarily via a page-down, is enough for me to make the descision to edit the query further or press "down" a couple of times, as I already know further refinement wouldn't be that useful.

**Comment by weilbith** [comment]
Yank history

**Comment by sunjon** [comment]
> Yank history

Yank history could be a wrapper around existing functionality in something like [nvim-miniyank](https://github.com/bfredl/nvim-miniyank), but I personally don't think Telescope should do the legwork itself.

What could be possible is a [vim-peekaboo](https://github.com/junegunn/vim-peekaboo)-a-like, showing the contents of registers and possibly a couple of actions you can perform on them.

**Comment by tami5** [comment]
@sunjon totally agree

**Comment by sharksforarms** [comment]
`:Telescope colorscheme` could display a preview with the selected scheme and the current bufffer

**Comment by weilbith** [comment]
Allow to configure `:drop` as default action on files.

**Comment by clason** [comment]
Emoji picker (as an extension)

Bonus points for including kaomoji ^_^

**Comment by sunjon** [comment]
An autocommands finder would be practical:

```
[group] | [event] | [pattern] |  [commands..........]
```
semi-related to this:
- the ability to pre-populate the query. Maybe with <cword> and such
- the ability to refine the search with something to specify fields. For this to be possible, Telescope would have to have more of a concept of "fields" than the few finders that use a `|` delimiter. a `cut` like `-f` parameter perhaps.
- If we were to introduce query parameters as mentioned above, perhaps notation like `!` and `^` and `$` would be useful, without the need for a full regex search

**Comment by cempassi** [comment]
A digraph picker. See `:digraph` to see the available ones. Really useful for us in Europe or Japan!

**Comment by ZacharyRizer** [comment]
A wrapper or choice to use FZF as the default for things like find files and grep. I'm loving Telescope, but fzf is still quite a bit faster in my experience.

**Comment by tami5** [comment]
> A wrapper or choice to use FZF as the default for things like find files and grep. I'm loving Telescope, but fzf is still quite a bit faster in my experience ( or maybe just more async to not have perceived freezing on big directory searches).
@ZacharyRizer  Have you checked https://github.com/nvim-telescope/telescope-fzf-writer.nvim, its still experimental though

**Comment by ZacharyRizer** [comment]
> > A wrapper or choice to use FZF as the default for things like find files and grep. I'm loving Telescope, but fzf is still quite a bit faster in my experience ( or maybe just more async to not have perceived freezing on big directory searches).
> 
> @ZacharyRizer Have you checked https://github.com/nvim-telescope/telescope-fzf-writer.nvim, its still experimental though, need testers :D

I have. For me it was still quite a but more sluggish than fzf, but I could have had it setup wrong.

**Comment by tami5** [comment]
@ZacharyRizer plz add comment in an open issue there, so it can be later fixed.

**Comment by clason** [comment]
`:messages`? with actions for `visual` selecting lines for copying etc?

**Comment by sunjon** [comment]
- The autocmd preview shows everything in the group, then highlights the active selection,
I think all highlights should be shown in a table, and 'preview-selection' jumps to the active result

- A Finder for available/installed luarocks packages.

**Comment by aca** [comment]
Feature Request
- After `:Telescope find_Files`, select multiple files, and open all in buffers / split / tab.

**Comment by ndavidpsi** [comment]
- Add `:Telescope media_Files`, it would search for files with media extensions (videos and images) and instead of opening the raw content of a file it would simply launch an external media player to load the file

**Comment by ndavidpsi** [comment]
- Add `:help Telescope`

**Comment by s-zeng** [comment]
Feature request: I think it would be nice if the nvim buffer previewer applies treesitter highlights to the previewed files

**Comment by Conni2461** [comment]
@s-zeng Actually we do apply tree-sitter highlighting if `nvim-treesitter` is installed and a `parser` is found for that filetype. And it works at least for `lua`, `c`, `cpp`, `python`, `sh`. But the filetype guesser in this repository parses `autocmd filetypedetect` and is really greedy so we get a wrong result for `rust` which leads to wrong highlighting. We are working on a new/better filetype guesser inside `plenary.nvim` which should help a lot. You can try it with both https://github.com/nvim-lua/plenary.nvim/pull/29 and https://github.com/nvim-telescope/telescope.nvim/pull/326. But that one might take a couple more days.

So there is a reason why it is `experimental`/`opt in` right now, its not perfect and we merged it to get more feedback from users. So it would be very helpful if you could open a bug report and i could take a better look at your issue. :)

Note: I will hide both comments after 24 hours. This is not the right place to discuss this issue. :)

**Comment by elianiva** [comment]
> * Add `:Telescope media_Files`, it would search for files with media extensions (videos and images) and instead of opening the raw content of a file it would simply launch an external media player to load the file

I would also love an option where if you open a binary file that's not supposed to be opened in neovim like png/jpg/webp, it will use `xdg-open` or just exits without opening anything. It's kinda annoying when I accidentally opened an image and it opens a buffer filled with those garbled weird texts.

**Comment by sharksforarms** [comment]
Snippet discover-ability: Using telescope to list available snippets (using completion source?)

**Comment by elianiva** [comment]
> > * Add `:Telescope media_Files`, it would search for files with media extensions (videos and images) and instead of opening the raw content of a file it would simply launch an external media player to load the file
> 
> I would also love an option where if you open a binary file that's not supposed to be opened in neovim like png/jpg/webp, it will use `xdg-open` or just exits without opening anything. It's kinda annoying when I accidentally opened an image and it opens a buffer filled with those garbled weird texts.

I think it would be really cool if telescope can use `ueberzug` as a previewer for image files, though it might get messed up if we jump between files too fast and the rendering might be slow on larger images. Other case is if we're trying to find an image, it will switch between files quickly because with the current behaviour, the first item gets selected and showed in preview window. I'm thinking of not previewing the image unless you press a mapping that confirms you want to see the image.

Since ueberzug spawns a child window, the previewer doesn't need to be a terminal, it can be a regular buffer. I found an interesting repo that does this. https://github.com/heapslip/vimage.nvim
I've tried it myself and seeing Neovim "draws" an image blows my mind :laughing: (technically ueberzug did it, but it draws it inside Neovim which I've never seen before).

![image](https://user-images.githubusercontent.com/51877647/103485703-e0ad9f80-4e2a-11eb-99c9-7823f9501871.png)

I don't know how hard it is to implement, it's just a random thought at 1 AM because I couldn't sleep :laughing:

**Comment by ndavidpsi** [comment]
@elianiva WOW! I fully switched to telescope.nvim now, I'm just waiting for some replies on the powershell previewer compatibility issue and then I'll start to work on :Telescope media_files. It shouldn't be hard to implement the external program version, I've done so in fzf.vim. However I can't say the same about internal rendering. Just wow I've dreamed about something like vimage for some time, I had no idea it was possible.

**Comment by relnod** [comment]
I would realy like it, if there was an option, to sort buffers by recently used. This would enable easier buffer switching.

**Comment by windwp** [comment]
@elianiva  #408

**Comment by 3nuc** [comment]
/<CR/> in :Telescope git_branches doesn't switch to the branch if it doesn't already exist in the output of `git branch`

eg.

```sh
$ git branch
* my_branch
   some_other

in nvim: :Telescope git_branches<CR> "select some branch that is not one of the two above and press CR

$ git branch 
* my_branch
   some_other
# nothing changed
```

However if you pressed  \<cr\> on some_other in the finder, it'd check out normally

**Comment by quantum-booty** [comment]
Fuzzy search a programming language's function signatures and their doc strings. idk if this is in the realm of a language server but it would be a nice feature.

**Comment by Conni2461** [comment]
Hey everybody,

we are closing the wishlist because it became a nightmare to manage.
We get bug reports and feature requests in the same issue and can't really chat about them because we tried to keep this issue as clean as possible. In addition, we also have a hard time knowing what feature requests are being worked on.

So we ask that you check to see if your request has been fulfilled, if not, check to see if an issue already exists, and if that's not the case either, open one using the new feature request template.

If you have questions about a telescope feature, you can reach us at [gitter](https://gitter.im/nvim-telescope/community). We currently have many features and options undocumented and we are working on a way to generate vim documentation here https://github.com/nvim-telescope/telescope.nvim/pull/370.
