### ISSUE TITLE
Ability to perform an action on an entry (edit) and display the updated value in the original finder 

### ISSUE THREAD

**Issue by sunjon** [nvim-telescope/telescope.nvim#276]
I'm creating a [register finder](https://github.com/nvim-telescope/telescope.nvim/pull/275).

One of the actions I would like to have is `edit`. I'm using input() for that at the moment and it works okay-ish.

I don't call action.close(), because I want the user to be able to continue using the finder, and maybe perform an action on another entry.

Currently, the register is updated, `entry.value` is updated and the finder is refocused, however it still shows the original pre-edited entry.

**Comment by l-kershaw** [comment]
I am guessing that `Picker:refresh()` is sufficient for this, so will close this now.

Feel free to reopen if you disagree 🙂

**Comment by smackesey** [comment]
`Picker:refresh()` works for this, but is there a way to restore the selection position? When I run `Picker:refresh()` with a new finder, my input text at the prompt stays the same, but the selection leaps back to the top of the results list. I tried saving the selected row index before and restoring it after I call `Picker:refresh()`, but this isn't working-- I'm assuming because Picker:refresh() runs asynchronously?

How would I restore the selection (it's not a multi selection, just the selected row)? Is there a way to "await" intil Picker:refresh finishes, or provide it a callback?
