### ISSUE TITLE
Can we have more options in builtin.buffers? 

### ISSUE THREAD

**Issue by kls1991** [nvim-telescope/telescope.nvim#2773]
**Problem:**
`Telescope buffers` is not flexiable as `:ls` because `:ls` accept flags as +|m|h|u etc...

**Solution:**
I find a function in lua\telescope\builtin\__internal.lua at line 885 called builtin.buffers.
It seems not hard to change but I don't konw how to make a pull request yet :)
Can we add a new key in builtin.buffers's parameter table like opts.bufnrs(a list of bufnr) or opts.filter(a function to filter all bufnrs)?
So users can have more control to which buffers to pick in, and they can make more flexible keymaps or user commands or whatever they want.

Sorry for my bad English.
I'm willing to learn enough skills to contribute one day!

**Comment by lrfurtado** [comment]
I would be intersted in implementing something that displays only the modified buffers could not find a way to do this with the current :Telescope buffers implmentation.

**Comment by kls1991** [comment]
> I would be intersted in implementing something that displays only the modified buffers could not find a way to do this with the current :Telescope buffers implmentation.

I'm willing to do something like this

```
vim.keymap.set("n", "<leader>x", function()
    -- get all modified buffers
    bufnrs = {}
    if vim.tbl_isempty(bufnrs) then
        vim.print("No modified buffers")
    else
        require("telescope.builtins").buffers { bufnrs = bufnrs }
    end
end)
```

**Comment by Conni2461** [comment]
regarding filtering, i'd talked about this a couple of times that i prefer if we wouldn't add a filter function to every single builtin like we did here (https://github.com/nvim-telescope/telescope.nvim/pull/2132) this was fine at the time but i'd prefer something like this: https://github.com/nvim-telescope/telescope.nvim/pull/2132#pullrequestreview-1071935517

Which I also mentioned here: https://github.com/nvim-telescope/telescope.nvim/pull/2258 and here: https://github.com/nvim-telescope/telescope.nvim/issues/2649 the first one actually implemented the possibility for filtering `builtin.buffers` but its always the same code (aka duplication) and its not as flexible.

My problem with implementing currently is that i'd like to use some iterator library and we could go with `plenary.iter` but `vim.iter` already exists but only on latest nightly. So i was lately thinking that for now we go with `plenary` and we are upfront that this feature is not stable and will be migrated to `vim.iter` after a 0.10 release. Because its very likely that telescope 0.2 will require neovim 0.10 (i pretty sure i will bump the minimum required neovim version for the next release).

Does that make sense?
