### ISSUE TITLE
add select_tab_drop as part of 0.1.5 release tag

### ISSUE THREAD

**Issue by zachvalenta** [nvim-telescope/telescope.nvim#2799]
`select_tab_drop` is on master but not in the `0.1.4` release tag. I'm finding this action very useful, seems like others are as well, but based on [this thread](https://github.com/nvim-telescope/telescope.nvim/issues/2188#issuecomment-1516861881) also seems like folks using master to access it (despite the warning in the README [advising against using master](https://github.com/nvim-telescope/telescope.nvim#installation)).

If there's a process to propose features from master that one would like to see in the latest release tag (beyond creating an issue) please let me know.

**Comment by jamestrew** [comment]
It will eventually make it to v0.1.5 (barring any major issues with it) but we don't have a regular cadence for release cycles so I'm not sure when that'll be.

If you're the kind to be on github creating issues/PRs, and you're fairly comfortable with vim package manager (you can roll back a commit if something broke) I think it's fine using the master branch. Or alternatively, you can pin yourself to this commit `20bf2050` if you'd rather not wait for 0.1.5.

**Comment by Conni2461** [comment]
> It will eventually make it to v0.1.5

no it will not be backported as i'd like to somewhat follow semversion: https://semver.org/

> PATCH version when you make backward compatible bug fixes

So for now only bug fixes are ported back, you have to wait till v0.2 or run master or write your own action.

v0.2 will need a little bit longer till its done, i'd like to include a little bit more in that release, and also do a little bit of breaking changes. (Yes thats the somewhat semver part, i'd also like to do breaking changes in the next minor version, because i dont think the next release is actually something i wanna call v1.0.0).

We suggest the last stable release or the stable branch because it allows us to do more on master without keeping every user in mind.
