### ISSUE TITLE
Buffers: Ignore `ignore_current_buffer` if only buffer

### ISSUE THREAD

**Issue by mizlan** [nvim-telescope/telescope.nvim#2831]
**Is your feature request related to a problem? Please describe.**

`ignore_current_buffer` is a great addition to `Telescope buffers` (see https://github.com/nvim-telescope/telescope.nvim/pull/444), but it causes Telescope to not open a window at all when there is only one buffer (since there ends up being 0 candidates).

**Describe the solution you'd like**

The current buffer should **not** be ignored if it is the only open buffer (i.e., in cases where if `ignore_current_buffer` weren't enabled, the Telescope results would only have one entry—the current buffer). In these situations it is better to display the singular candidate than to fail to open Telescope at all, which can be jarring.

The above is subjective but I think it makes the most sense.

**Comment by mizlan** [comment]
Never mind, I don't like this idea as a default but I wrote a patch for myself

```diff
@@ -884,6 +884,7 @@ end
 
 internal.buffers = function(opts)
   opts = apply_cwd_only_aliases(opts)
+  local cur_buf = vim.api.nvim_get_current_buf()
   local bufnrs = filter(function(b)
     if 1 ~= vim.fn.buflisted(b) then
       return false
@@ -892,7 +893,7 @@ internal.buffers = function(opts)
     if opts.show_all_buffers == false and not vim.api.nvim_buf_is_loaded(b) then
       return false
     end
-    if opts.ignore_current_buffer and b == vim.api.nvim_get_current_buf() then
+    if opts.ignore_current_buffer and b == cur_buf then
       return false
     end
     if opts.cwd_only and not string.find(vim.api.nvim_buf_get_name(b), vim.loop.cwd(), 1, true) then
@@ -904,7 +905,11 @@ internal.buffers = function(opts)
     return true
   end, vim.api.nvim_list_bufs())
   if not next(bufnrs) then
-    return
+    if 1 == vim.fn.buflisted(cur_buf) then
+      bufnrs = {cur_buf}
+    else
+      return
+    end
   end
   if opts.sort_mru then
     table.sort(bufnrs, function(a, b)
```

**Comment by jamestrew** [comment]
Probably a message saying something like "only current buffer exists" would be helpful.

**Comment by lrfurtado** [comment]
I can help here , let me play with this and put a PR up

**Comment by jamestrew** [comment]
I kinda addressed this in https://github.com/nvim-telescope/telescope.nvim/commit/c621f71012459ccbe63e625169bfe36889692522

There could be many reasons for why you might not get a list of buffers depending on the options passed. At least with that commit, you'll get a message indicating that as opposed to silently not opening telescope.

I think the original request of ignoring options that make it so telescope doesn't open due to a lack of results is probably undesirable in many cases especially as a default like you say.

I think we can close this issue. Open to questions if you have any.

**Comment by mizlan** [comment]
I am in full agreement. Thanks!
