### ISSUE TITLE
If `Current Buffer Fuzzy` found only 1 entrance move cursor to it 

### ISSUE THREAD

**Issue by dmtrKovalenko** [nvim-telescope/telescope.nvim#2904]
## Problem

Right now if you have a situation like that and you select the first entrance you the location 6:1 will be selected (meaning the start of the 6th line):

<img width="997" alt="image" src="https://github.com/nvim-telescope/telescope.nvim/assets/16926049/22b6bfbd-5628-4924-ae9a-d7f134418282">

this is annoying because I precisely searched for plenary and I expect my cursor to be at the `p` in this case  but I need to additionally jump to the word

<img width="574" alt="image" src="https://github.com/nvim-telescope/telescope.nvim/assets/16926049/5fa6006e-24c9-4e21-8e25-18a09b17f4e0">

## Solution

Taking into account that the telescope already knows how the line was matched (we are highlighting matching parts with blue) — I propose to move the cursor to the first matched entrance.

Alternatively we can move cursor to entrance only if there is 1 match per line but it might not fully cover the problem in case like this when you for instance missed or misspelled some part of the word
<img width="1024" alt="image" src="https://github.com/nvim-telescope/telescope.nvim/assets/16926049/901111de-164a-45e3-82d5-e7bc1928aad7">

**Comment by jamestrew** [comment]
Hmm... I kind of like this idea but I think it would be tricky since the mechanism to create the entry (the value to search, where to go lnum/col/file when selected) is not very local to the mechanism for highlighting the match (more related to the sorter).

It's doable but would need some thought into how to distinguish between pickers/entry_makers that would implement this versus those that don't. 

But maybe the bigger question is if this is even actually intuitive behavior.
Considering it's a fuzzy finder, I think it's fair to expect that what you type (the prompt) versus what you're searching for isn't always a one to one match. If it is, then you would just use vim's `/` search.

Kind of a bad example but
![image](https://github.com/nvim-telescope/telescope.nvim/assets/66286082/9dc027bf-9cd4-416b-bafc-f91ce95a60aa)
in this case, jumping to `l` isn't really our intent (jumping to the `p`). In this case it's better than the start of the line but I can imagine situations where it wouldn't be.

**Comment by dmtrKovalenko** [comment]
I personally always confused by this because I use telescope search only to avoid typos when I don't know how identifier looks or for some generic stuff. 

And when you see a preview highlight for me personally in 100% of cases I expect cursor be on the matched occurrence

**Comment by antonk52** [comment]
Just published a PR that should improve this #2909

**Comment by dmtrKovalenko** [comment]
Arghh I actually hoped to make my second contribution, but you made it first! Thanks for such a quick PR this gonna be really handy for my workflows :)

**Comment by jamestrew** [comment]
closed by #2909
