### ISSUE TITLE
finder fuzzy filter

### ISSUE THREAD

**Issue by Marskey** [nvim-telescope/telescope.nvim#2913]
I am wondering how to add this feature [rg-fzf](https://github.com/junegunn/fzf/blob/master/ADVANCED.md#switching-between-ripgrep-mode-and-fzf-mode-using-a-single-key-binding)

use `fzf` to filter the results of `rg`, it could be useful

**Comment by jamestrew** [comment]
For `live_grep` we have an action bound to `<C-space>` to fuzzy find over the results of rg.
There's no mechanism to then go back to further filtering the results filtered by fzf with rg again (rg->fzf->rg). It's only a one time switch but I think in 99.9% of cases, this is enough.

**Comment by Marskey** [comment]
This hint is very helpful for me. thank u

**Comment by OJFord** [comment]
That's not the same thing at all?

For one thing if you want to fuzzy search for say 'gthub' that means starting the query with <kbd>g</kbd>, then <kbd>Ctrl</kbd>-<kbd>Space</kbd>, then continuing.

But it's not even the same as a fuzzy search for 'gthub', because now 'g' could be anywhere, so we're fuzzy finding 'thub' over results that include say 'thubg'.

---

I realise as I type this that a 'solution' is to make the initial rg query `.`, but now it's an even longer process to get to the fuzzy search.

**Comment by jamestrew** [comment]
@OJFord I believe the request was for the ability to toggle the results of rg to a fzf search based on the link.

If you're looking for a purely fuzzy search like Ag or something, there are other issues covering that. I can't find them on my phone right now. But there's a workaround to achieve it better than your approach.

**Comment by OJFord** [comment]
Oh yes sorry I misread OP here.
