### ISSUE TITLE
Keymap <S-s> does nothing when input is empty.

### ISSUE THREAD

**Issue by Endermanbugzjfc** [nvim-telescope/telescope.nvim#2919]
### Description

The normal mode mapping `<S-s>` in vanilla Vim is designed to truncate the whole line and return to insert mode, similar to the `ddo `command. I prefer using this mapping over `i` because it ensures a clear input regardless of the current state. However, I've encountered an issue where this mapping only works if the input of a picker window is not empty. If the picker window input is empty, the mapping does nothing.

### Neovim version

```markdown
NVIM v0.9.5
Build type: RelWithDebInfo
LuaJIT 2.1.1703942320
```

### Operating system and version

Windows 11 Home 21H2 22000.1936

### Telescope version / branch / rev

telescope 0.1.5

### checkhealth telescope

```markdown
==============================================================================
telescope: require("telescope.health").check()

Checking for required plugins ~
- OK plenary installed.
- OK nvim-treesitter installed.

Checking external dependencies ~
- OK rg: found ripgrep 14.1.0 (rev e50df40a19)
- OK fd: found fd 9.0.0

===== Installed extensions ===== ~

Telescope Extension: `terms` ~
- No healthcheck provided

Telescope Extension: `themes` ~
- No healthcheck provided

Telescope Extension: `ui-select` ~
- No healthcheck provided
```

### Steps to reproduce

1. Run `:Telescope` to activate an arbitrary picker window.
2. Press `<Esc>` to enter normal mode.
3. Press `<S-s>`.

### Expected behavior

Returns to insert mode.

### Actual behavior

Nothing happened.

### Minimal config

The following command directly reproduces the minimal environment with lazy.nvim and Telescope v0.1.5:
```bash
docker run -w /root -it --rm alpine:latest sh -uelic '
  apk add git neovim --update
  mkdir -p ~/.config/nvim
  cat > ~/.config/nvim/init.lua <<EOF
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable", -- latest stable release
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)

require("lazy").setup({
  {
    "nvim-telescope/telescope.nvim",
    dependencies = { "nvim-lua/plenary.nvim" },
    cmd = "Telescope",
    tag = "0.1.5",
  },
})
EOF
  nvim --cmd ve
  '
```

**Comment by jamestrew** [comment]
This is a limitation/intended behavior of Vim's `buftype="prompt"` that we're using - this disables normal mode command for everything except the last line of the buffer after the prompt (ie the prompt without entering anything).

I'm not sure there's motivation to change this on our end any time soon. I think prompt buffers offers us a few conveniences while giving us good UX for insert mode which is our main focus over normal mode.

From `:h prompt-buffer`:
> If you want to type input for the job in a Vim window you have a few options:
> - Use a normal buffer and handle all possible commands yourself.
  This will be complicated, since there are so many possible commands.
> - Use a terminal window.  This works well if what you type goes directly to
  the job and the job output is directly displayed in the window.
  See |terminal|.
> - Use a window with a prompt buffer. This works well when entering a line for
  the job in Vim while displaying (possibly filtered) output from the job.
