### ISSUE TITLE
Find next and previous occurrences with `current_buffer_fuzzy_find()`

### ISSUE THREAD

**Issue by sand4rt** [nvim-telescope/telescope.nvim#2970]
Thanks for the awesome plugin!

Would it be possible to incorporate functionality into the plugin that allows for the navigation between next and previous occurrences using `shift n` and `n` when using `require("telescope.builtin").current_buffer_fuzzy_find()`?

**Comment by Conni2461** [comment]
i agree with james here, i dont see a reason why we want to add this. primiarly because we are a fuzzy finder, implementing this would require us to keep state for long after its already closed and stuff like this, which just isnt worth it. But what you can do is just send everything to qflist and den use bindings for `cn` and `cp`. this works with most pickers and is not just a one of thing

**Comment by sand4rt** [comment]
Thanks for the responses! I'm still curious if it's possible to use something like`vim.fn.setreg('/', 'THE_ACCEPTED_RESULT_FROM_TELESCOPE')` right after pressing `enter` on a search result within `current_buffer_fuzzy_find()`.

By the way, I'm using `vim.o.cmdheight = 0` and aiming to replace the `/` and `?` with `current_buffer_fuzzy_find()`. Using a qflist feels a bit too manual for this.

**Comment by Conni2461** [comment]
hmm yeah thats a good argument, we could use `setreg` for that, because i think we can pass a list that points to locations (actually similar to qflist), as a separate action. you can maybe provide a PR that implements it, and we can look at it and discuss again if this is a good place for that, alternativly you can keep this action in your configuration.

take a look at the developers guide: https://github.com/nvim-telescope/telescope.nvim/blob/master/developers.md for how to get started and maybe this action for inspiration: https://github.com/nvim-telescope/telescope.nvim/blob/dc1ea28cc2a02cd1cebb9d80e967807d668f78f8/lua/telescope/actions/init.lua#L941

**Comment by sand4rt** [comment]
Thanks for the pointers. I hacked this together, but I don't think this is worth a PR. If anyone knows a better way to implement this, please let me know!

```lua
{
    '/',
    function()
        require("telescope.builtin").current_buffer_fuzzy_find({
            attach_mappings = function(prompt_bufnr)
                -- TODO: pass search results to setreg instead of the prompt
                local actions = require("telescope.actions")
                actions.select_default:replace(function()
                    local action_state = require("telescope.actions.state")
                    local prompt = action_state.get_current_line()
                    local entry = action_state.get_selected_entry()
                    if prompt then
                        vim.fn.setreg('/', prompt)
                    end
                    actions.close(prompt_bufnr)
                    vim.api.nvim_win_set_cursor(0, { entry.lnum, entry.index })
                end)
                return true
            end,
        })
    end,
},
```

**Comment by Conni2461** [comment]
yeah but this doesnt work for fuzzy find prompts :thinking: 

if it now works for you thats great but i dont see us implementing this solution here

**Comment by sand4rt** [comment]
> yeah but this doesnt work for fuzzy find prompts

I know, the solution is not ideal, but is all I was able to get working with limited lua/vim knowledge. Would be nice if someone could come up with a better solution.
