### ISSUE TITLE
man_pages to support listing man pages for word under cursor

### ISSUE THREAD

**Issue by dsirov** [nvim-telescope/telescope.nvim#3278]
`:Telsecope man_pages` currently lists all man pages (from ALL or specific sections).

It would be nice if there was an option for a programmer to list all relevant man pages for the (API) word under cursor in the source code.

For example, for open(...), the list will be:

- open (3pm)
- open (2)

Proposal: add a boolean option `cword`, that if true, would only show man pages for words under cursor.
`:Telescope man_pages cword=true`

**Comment by jamestrew** [comment]
would something like this suffice?
```lua
require('telescope.builtin').man_pages({ sections = { 'ALL' }, default_text = vim.fn.expand('<cword>') })
```

**Comment by Conni2461** [comment]
there is nothing to do here, this is currently already possible. and the current solution is much more flexible rather than only an explicit cword option because it allows you to define how you want to execute the apropos call.

Otherwise we would need to add even more options for regex, exact, full word matching etc ... You can use the following keymap if you are on an linux based system. I dont know if it also works on darwin/feebsd or if you have to slightly modify that command. You can test that with your cli

```lua
vim.keymap.set("n", "<leader>om", function()
  require("telescope.builtin").man_pages({
    sections = { "ALL" },
    man_cmd = { "apropos", "-r", "^" .. vim.fn.expand('<cword>') .. "$" }
  })
end, { noremap = true })
```
