### ISSUE TITLE
[suggestion] use vim movements in results/preview window

### ISSUE THREAD

**Issue by hoob3rt** [nvim-telescope/telescope.nvim#403]
I don't know if this has been discussed but I think it would be nice to use vim movements in results window. This "normal" mode is really limited...

Say you live grep something and see your result on top of the result window, now you have to hold `k` and wait instead of pressing `gg` or `H`. Range operators would also be nice e.g. `10k`.

This is a problem in all fuzzy finders for vim I know and it doesn't feel vim-like but since telescope is so close to neovim core I think it would be a nice feature to have. 

As of `<C-u>` and `<C-d>` I think scrolling in preview window is more of a gimmick than a feature but I understand it could be useful for someone. Imo there should be an option to switch between results and preview window using `<C-w>hl>` and use all normal mode movements in both.

Let me know what you think :)

**Comment by Conni2461** [comment]
That are some really good suggestions.
1. `G` or `gg` should be super easy to realize. We only have to do a `shift_current_selection` with the amount of lines currently displayed or 0. After that mapping the function is trivial
2. The second suggestion(10k) should be relative easy to do as well and should be a really good addition. I just need to figure out if we can get `v:count`. Have not tried it in lua yet.
3. This one is tricky(previewer). Switching window focus is super easy. Don't get me wrong. We are doing it all the time for example `help_tags` to get to the correct position we are doing a `vim.fn.search`. So let me explain the tricky part.
We have two base_previewers. One based on `termopen` which will start `cat` or `bat`. With this one we are basically pretty limited. If `less` is installed we have a pager so you should be able to do searching and jumping not that interesting. 

With the experimental `buffer_previewer` we can do all most of stuff. Everything that we can do in a real buffer besides actually edit the file. And thats the point that will be hard for people to understand. This file we are looking at is just the content of the file and the buffer has actually no relation with any file. Why? Because if we do something like `bufload` which loads the file into the buffer we will end up running all autocmds. Synchronously. Which means everything blocks when moving though your results. So our solution right now is reading the file async with `uv.fs_open` ... and attaching the highlighter to the buffer. So to make the file editable we have to actually overwrite the whole file on save by ourselves and i am not really happy with that.

But we actually discussed making buffer_previewer editable and doing some other cool stuff. @sunjon suggested this in telescope gitter on December 29 2020:

> I've wanted to know what the fascination with org-mode is for a while. I've not used emacs, and org-mode get mentioned far more as a "thing", rather than "it's great because x,y and z"
but on a reddit thread yesteday, someone actually described the functionality they were missing:
this org-mode feature allowed them to pull all of the // TODO: foobar comments from their project dir
and then on selection, allow them to edit them
I was thinking this; 1) find project files, 2) parse language comments with TS, 3) filter and list todo's. 4) allow selection and take sha hash of file before you make your pseudo edit 5) make sure hash is still the same, and commit to file
the feature, is that I wanted to do the editing, in the preview window
maybe convert it to something else, for the duration of the edit
it's still along the lines of some modal thing, that the vim-options finder needed.
I think it could be a useful feature
doesn't have to be limited to TODO, but it seems the best candidate to begin with

**Comment by hoob3rt** [comment]
>     1. `G` or `gg` should be super easy to realize
>     2. The second suggestion(10k) should be relative easy to do as well

That's great to hear! I would love to see them implemented. Using only repeated `j` and `k` is really painful especially in `:Telescope lsp_code_actions`.

>     3. This one is tricky(previewer). 
It indeed is tricky, but it would be insane and make telescope the best fuzzy finder if it also supported quick edits imo :)

**Comment by fdschmidt93** [comment]
I'd say solved, please comment or better yet raise a detailed feature request in case there's anything to do here.
