### ISSUE TITLE
git_files shows submodules

### ISSUE THREAD

**Issue by timbedard** [nvim-telescope/telescope.nvim#410]
### Description
The `git_files` picker shows git submodules. This is both annoying and can break previewers that are expecting to act only on files, such as the new `vim_buffer_cat` previewer.

I haven't found a suitable option for `git ls-files` or an alternative single command that gives us what we want, so we might just need to filter out the submodules from the list. From cursory exploration, it looks like we can use the output of `git submodule status` or just parse `.gitmodules` to determine what the submodules for the repo are.

Alternatively, `git grep --exclude-standard --cached --untracked -l ""` comes _really_ close, but excludes empty files and symlinks as well.

**Expected Behavior**
The `git_files` picker does not show git submodules.

**Actual Behavior**
The `git_files` picker shows git submodules.

### Details

<details><summary>Reproduce</summary>

1. Open nvim in a git repo with one or more submodules.
2. `:Telescope git_files`

</details>

<details><summary>Environment</summary>

- nvim version: v0.5.0-dev+b535575ac
- Operating system: macOS
- Telescope commit: de80a98

</details>

<details><summary>Configuration</summary>
<p>

(default)

```viml
set nocompatible hidden laststatus=2

if !filereadable('/tmp/plug.vim')
  silent !curl --insecure -fLo /tmp/plug.vim
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

source /tmp/plug.vim
call plug#begin('/tmp/plugged')
Plug 'nvim-lua/popup.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
call plug#end()

autocmd VimEnter * PlugClean! | PlugUpdate --sync | close
lua << EOF

require('telescope').setup{
  defaults = {
    vimgrep_arguments = {
      'rg',
      '--color=never',
      '--no-heading',
      '--with-filename',
      '--line-number',
      '--column',
      '--smart-case'
    },
    prompt_position = "bottom", 
    prompt_prefix = ">",
    selection_strategy = "reset",
    sorting_strategy = "descending",
    layout_strategy = "horizontal",
    layout_defaults = {},
    file_ignore_patterns = {},
    shorten_path = true,
    winblend = 0,
    width = 0.75,
    preview_cutoff = 120,
    results_height = 1,
    results_width = 0.8,
    border = {},
    borderchars = { '─', '│', '─', '│', '╭', '╮', '╯', '╰'},
    color_devicons = true,
    use_less = true,
  }
}
EOF
```

**Comment by Conni2461** [comment]
Okay i see what you are saying. The bug, why its crashing, is in plenary so i messed up something there :|

There is a PR https://github.com/nvim-telescope/telescope.nvim/pull/329 which allows you to display submodules content but thats not what you expect so i was planing to do a ls for `vim_buffer_cat`, currently we have that in `term_previewers` but not for the new once. I was talking about it here https://github.com/nvim-telescope/telescope.nvim/pull/395#discussion_r552221839.

The easy way would be to just run ls but i think we can do this just with `vim.loop.fs_` and i am really close to finishing it https://github.com/nvim-lua/plenary.nvim/pull/45.

Maybe that will help in the future because i am not sure if we can realize that submodules are not shown at all.

**Comment by timbedard** [comment]
Ah, word. I searched issues, but I guess I forgot to search PRs. Looks like you've got adherence to gitignore in there too. Kudos.

Bummer about the CI.

**Comment by Conni2461** [comment]
No worries. Still grateful about the issue. Didn't know that directory was crashing again.

CI comes back :) just need a nvim nightly image on github to pull.

The original plan with my PR was to have a fd replacement written in lua and `respect_gitignore` was only directed for that.
The ls replacement was not meant to have `respect_gitignore` but because its based on the fd replacement now, just with `depth = 1` and long format, its possible to enable that feature. We probably wont for the `buffer_previewer` but you could just replace the `previewer_file_maker` and enable that opt. But that Music of the future.

I am planing to finish that directory previewer over the next week. I just pushed a first draft and updated the PR description with a preview of the output. Hardest part is converting the uid / gid to the actual name without leaving lua land and running `id -nu`.
And i have to test on a windows machine 😆

**Comment by timbedard** [comment]
Roger that.

For the time being (and for anyone else who runs across this), I'm able to get what I want (git repo files sans submodules with the new buffer preview) easily enough by writing a quick project files picker function that just uses the regular `find_files` from the git root:
```lua
local M = {}
...
M.project_files = function()
  require("telescope.builtin").find_files {
    cwd = require("lspconfig.util").root_pattern(".git")(vim.fn.expand("%:p"))
  }
end
```
I just used `root_pattern()` from nvim-lspconfig for simplicity.

**Comment by Conni2461** [comment]
Okay i think we are done with this now. We can list submodules and show dirs in the buffer previewer. 
If you still wanna pass different opts to `ls_async` tell me and i can tell you how to do so.
If you have any issues feel free to reach out to me.

About your point of fallback to find_files if no git repo you can write that function:
```lua
M.project_files = function()
  local opts = {} -- define here if you want to define something
  local ok = pcall(require'telescope.builtin'.git_files, opts)
  if not ok then
    require'telescope.builtin'.find_files(opts)
  end
end
```

Thanks for reporting and your insight :)

Closing for now. Feel free to reopen if anything is left :)

**Comment by timbedard** [comment]
Hmmm. I'm actually getting this for `git_files` when it tries to preview the submodule dir:
```
Error executing luv callback:                                                                                                                                                                          
...e/pack/packer/start/plenary.nvim/lua/plenary/scandir.lua:239: table index is nil
```

**Comment by Conni2461** [comment]
https://github.com/nvim-lua/plenary.nvim/pull/55

Should at least fix it but there is another issue. You are on a mac right? Accordning to google i can't read passwd for the usernames and ids :| So i can go from id to name. Didn't know about that 😆 

I do some more digging later today. Sorry for the inconvenience :)

**Comment by Conni2461** [comment]
I doing another confident close here. Hopefully that doesn't jinx it 😆 

Thanks for the testing @timbedard :)

**Comment by timbedard** [comment]
Thanks for the good work! 😁

**Comment by motorto** [comment]
The fallback to find_files if no git repo is found seems to no longer work:

```
			project_files = function()
				local opts = {} -- define here if you want to define something
				local ok = pcall(require "telescope.builtin".git_files, opts)
				if not ok then require "telescope.builtin".find_files(opts) end
			end

			local Opts = { noremap = true, silent = true }

			vim.api.nvim_set_keymap('n', '<leader>ff', '<cmd>lua project_files()<cr>', Opts)

```

![image](https://user-images.githubusercontent.com/52639805/193420584-ab43322e-ea5d-4e80-9e99-3200a67348f9.png)

**Comment by motorto** [comment]
@bangedorrunt Thanks the workaround indeed works, update the recipe on the wiki so that no one stumbles on this again would be appreciated
