### ISSUE TITLE
ENOENT: no such file or directory on [No Name] buffer

### ISSUE THREAD

**Issue by numToStr** [nvim-telescope/telescope.nvim#411]
### Description
Following command gives error on `[No Name]` buffer. I don't know what this buffer is called.
```lua
require('telescope.builtin').buffers()
```

![image](https://user-images.githubusercontent.com/24727447/104117164-2e536c00-5345-11eb-8571-0478454bb56e.png)

**Expected Behavior**
Ignore `[No Name]` buffer.

**Actual Behavior**
Gives error

**Comment by Conni2461** [comment]
Oh yeah. That was a required feature and it was working great, then i rewrote the `previewers` so they are more consistent and introduced `buffer_previewer` and now its broken because we expect a file. I need to think how we can make it work again because i think having unnamed buffers is kinda a cool feature :)

But if you want to disable it locally you have to do change this line https://github.com/nvim-telescope/telescope.nvim/blob/de80a9837cd1d207981c1f6dbf504436f8bfee13/lua/telescope/make_entry.lua#L485
to something like this
```lua
if entry.file.name == '' then return nil end
local bufname = entry.info.name
```

Note: I haven't tested it so it might not work 🤣

**Comment by numToStr** [comment]
@Conni2461 No worries, I was just playing with telescope and find this issue.

**Comment by akinsho** [comment]
@Conni2461 I just ran into a very similar issue to this one. I think there is a broader issue which is that the previewer fails if there is no underlying files since it seems to be trying to open a file. I have some log buffers open whilst developing which have a buftype of `nofile` and this causes the same error.

I don't know if a more general solution is possible than checking for a bunch of different attributes e.g. `name` or `buftype` is it possible to try the specific function in a `pcall` and if it fails then just show some fallback message

I can open a separate issue but it seemed to be the same to me just in a different file

**Comment by Conni2461** [comment]
@akinsho Thanks for reaching out to me about that. I have a PR that gets rid of the `error` at least, i forgot to merge 😆. So it should atleast no longer error.

I know that the issue is way broader, i kinda wrote most of the buffer previewer and they work great as long as there is a file i can read 😆. The best solution would be writing a new previewer but that would also require a new `buffer_previewer` interface. Thats also why i am not happy with the fix we got 😆. 

I just added `buftype == 'nofile'` to that PR, so would be great if you could give it a try then i will merge :] #432

**Comment by akinsho** [comment]
@Conni2461 👍🏿 I just tried it and it seems to prevent the error, but prints out a message about not being able to open the file. It's definitely an improvement 🚀 . FWIW I don't really think I need to see that error, I think if there isn't an underlying file fair enough I dont really need a warning since I can't and won't really do anything about that

**Comment by Conni2461** [comment]
@akinsho I still wanna show you your buffer, so the message woudn't shown at that point but we still wanna output the error so people can open issues and report back with stuff like this :)

Just pushed a new version which should probably cover your case. Can you test again? Thanks :)

**Comment by akinsho** [comment]
Just tried again 👍🏿 seems to be working well
