### ISSUE TITLE
History/MRU picker

### ISSUE THREAD

**Issue by kristijanhusak** [nvim-telescope/telescope.nvim#433]
**Is your feature request related to a problem? Please describe.**
I switched from fzf, and one source that I miss the most is `:History`, which lists oldfiles + buffers (sorted by MRU).

**Describe the solution you'd like**
I'd like to have a separate picker that holds these.

**Describe alternatives you've considered**
I didn't find a solution for this so I implemented it myself in a same way fzf does it. Here are part of codes:
* Saving buffers: https://github.com/kristijanhusak/neovim-config/blob/bleeding-edge/nvim/lua/partials/telescope.lua#L12-L27
* Picker: https://github.com/kristijanhusak/neovim-config/blob/bleeding-edge/nvim/lua/partials/telescope.lua#L47-L83

I wanted to check if you would be interested in adding this here, and if yes, I could make a PR with the implementation.

**Comment by Conni2461** [comment]
Thanks for the request.

@sunjon was working on a "smart" MRU based on that [article](https://slack.engineering/a-faster-smarter-quick-switcher/) which should be almost done.
He can tell you more :)

**Comment by kristijanhusak** [comment]
Oh, nice :)
Is there a related issue/PR that I can track? I wasn't able to find anything related to MRU.
I guess I'll just stick with my version until smarter one is finished :)

**Comment by sunjon** [comment]
Hi. It's WIP (as in not usable yet), but I've put the repo up [here](https://github.com/sunjon/telescope-frecency).
The todo's are listed in the readme, and I'll move the project to the 'nvim-lua' namespace when it's complete.

Hope to have it in a testable order in the next couple of days.

**Comment by sunjon** [comment]
Closing this as the frecency MRU finder has [been released](https://github.com/nvim-telescope/telescope-frecency.nvim).
Hope it satisfies your requirements!

**Comment by kristijanhusak** [comment]
Thanks, I'll give it a try.

**Comment by kristijanhusak** [comment]
I gave this a test, it is working fine, but it doesn't work exactly how I'm used to it. If I open a file that I never opened before, I expect it to be first in the list when I open up the picker, which is not the case with this one. Of course, that's how it works by design, so no complains there :) I'll stick with my implementation. If someone shows interest in using my implementation I'll make a separate package for that.
Thanks anyway.

**Comment by jesseleite** [comment]
Hey @kristijanhusak, seconded, and thank you for sharing this!  @Conni2461 @sunjon, I think the frecency thing is really cool, but it's different than MRU...

**Frecency** = Frequency + Recency
**MRU** = Recency only

PS. @kristijanhusak curious though regarding your `save_buf()` + `remove_buf()` + autocommand buffer tracking...

1) I always found fzf's remove buffer functionality within `:History` confusing. Whether or not I close a buffer, I would still expect it to show in `:History`, since I did in fact open it. If I restart Vim, it would be in the oldfiles list, so why not leave it in the list, even after closing buffers?

2) Why not instead parse `:buffers t` (the `t` flag lists buffers sorted by time last used), and then filter the results by `filereadable()`? I'm curious if there is a reason why you're manually tracking buffers to a variable in memory?

**Comment by kristijanhusak** [comment]
@jesseleite I mostly copied how FZF works, but you have the point.
I'm not sure if there is a way to list buffers as `:buffers! t` through code. It's really hard and nasty to read output of the command line.

**Comment by jesseleite** [comment]
@kristijanhusak ^ Check the PR there when you have a chance! I'm parsing `:buffers! t` output fairly easily. Works just like fzf's `:History` now, but without the awkward remove-buffer functionality.

**Comment by kristijanhusak** [comment]
@jesseleite Awesome! I'll gladly replace my custom functionality for this.
