### ISSUE TITLE
Telescope leaves behind stale conhost processes on Windows 10

### ISSUE THREAD

**Issue by jacquesh** [nvim-telescope/telescope.nvim#459]
### Description
When telescope spawns process for previewing on Windows, it leaves behind the instance of conhost.exe. A new conhost is created (and left behind) every time telescope is run, meaning that after a while there are many, many conhost's lying around. I have `bat` available so telescope uses that, but if I remove `bat` and let it default to `less`, I still get the same behaviour.

I have confirmed that I don't see this with fzf (suggesting that this is not a general failure of neovim to correctly shutdown child processes).

**Expected Behavior**
After Telescope is closed, all processes that it spawned should terminate.

**Actual Behavior**
Each time Telescope is opened, it leaves behind a new conhost.exe instance.

### Details

<details><summary>Reproduce</summary>

1. nvim -nu test.vim
2. Run `:Telescope find_files`
3. Double-tap escape to close the telescope window
4. Notice that `conhost.exe` is still running as a child process to nvim (this is easy to see in something that shows a process tree, such as SysInternals' ProcessExplorer).
5. Optionally, go back to step 2 and repeat to see the ever-growing list of old conhost processes
</details>

<details><summary>Environment</summary>

- Telescope version: 099910d
- OS: Windows 10 1909
- nvim version:
<p>

```
NVIM v0.5.0-dev+1048-g69103ff0c
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 /MD /Zi /O2 /Ob1 /DNDEBUG /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -ID:/a/neovim/neovim/build/config -ID:/a/neovim/neovim/src -IC:/projects/nvim-deps/usr/include -ID:/a/neovim/neovim/build/src/nvim/auto -ID:/a/neovim/neovim/build/include
Compiled by runneradmin@fv-az152-352
Features: -acl +iconv +tui
See ":help feature-compile"
system vimrc file: "$VIM\sysinit.vim"
fall-back for $VIM: "C:/Program Files/nvim/share/nvim"
Run :checkhealth for more info
```
</details>

<details><summary>Configuration</summary>
<p>
This obviously won't work as-is on Windows but I'll stick to the template (no special configuration is needed to reproduce this)

```viml
set nocompatible hidden laststatus=2

if !filereadable('/tmp/plug.vim')
  silent !curl --insecure -fLo /tmp/plug.vim
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

source /tmp/plug.vim
call plug#begin('/tmp/plugged')
Plug 'nvim-lua/popup.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
call plug#end()
```

**Comment by Conni2461** [comment]
I remember someone on gitter saying the same thing applies on linux but i couldn't track down the issue. We clean up all processes and clear all buffers.
Also we kinda moved to the `buffer_previewers` in the past 2 months and i was working towards making them default and deprecating the `bat`/`less` previewers #420. So i suggest you add this to your config:

```lua
require('telescope').setup {
  defaults = {
    file_previewer = require'telescope.previewers'.vim_buffer_cat.new,
    grep_previewer = require'telescope.previewers'.vim_buffer_vimgrep.new,
    qflist_previewer = require'telescope.previewers'.vim_buffer_qflist.new,
  }
}
```

**Comment by jacquesh** [comment]
@Conni2461 oh great, that worked for me. Thanks!

That covers my immediate use-case then. Without knowing anything about Telescope's internals I would be concerned that the same issue would crop up if somebody configured a custom previewer, but if that's not a concern then I guess we're all done here :)

**Comment by Conni2461** [comment]
There are two option to start a custom previewer.
- `term_open_previewer`
- `buffer_previewer`
- or someone could write their own base previewer

We have a all 3 previewers, `file`, `grep` and `qflist` configured for both and extensions can easily reuse them and use the user configured ones. A lot of extensions under `nvim-telescope` org do that.

But also a lot of finders use `buffer_previewer` for specific things that won't work in the `term_open_previewer`. E.g. `Telescope help_tags` which needs to do a search to find the tag in the file.
And a lot of extensions define their own buffer_previewers as well. E.g. [octo.nvim](https://github.com/pwntester/octo.nvim) or [telescope-cheat](https://github.com/nvim-telescope/telescope-cheat.nvim) because they have the ability to keep the last buffer and just use that buffer if a selection is done.

Also we have a way to write stuff from an external job to the `buffer_previewer` example would be `Telescope man_pages`

So i wouldn't really be concerned right now that people write more previewers based on `term_open` especially if we change the default :)
