### ISSUE TITLE
question: how to search from git root folders

### ISSUE THREAD

**Issue by matu3ba** [nvim-telescope/telescope.nvim#468]
The README does not give advice, how to search for git root folders (in case of normal git project or git submodules).

Can you give me advice, how to set this up (without defining the folder path for each project that one works on)? 
I know there is `git rev-parse --show-toplevel` and `git rev-parse --show-superproject-working-tree`, but I am not sure how to invoke telescope the right way to search from there (and being able to open the right files etc).

I would also like to add a PR to the README, since this is a quite common use case.

**Comment by Conni2461** [comment]
I don't really get your question.

But we have `Telescope git_files` which will search for all files in your git directory based on your current working dir. You can also do `Telescope git_files cwd=/home/asdf/projects/telescope.nvim` if you want to look at files from another repo

**Comment by matu3ba** [comment]
@Conni2461 This does not work for git submodules, but it should be good enough. Why is it not called `Lists files from git root directory as current directory` ?

**Comment by matu3ba** [comment]
@Conni2461 
Meta: How can I copy the file paths?

**Comment by sunjon** [comment]
> @Conni2461
> Meta: Is there a way to copy file paths from the file picker, ie for usage in a system shell etc?

Take a look in the actions.lua file. There are `actions.send_to_qflist` and `actions.get_selected_entry` that are close to what you want (or you can create your own action).

**Comment by Conni2461** [comment]
> This does not work for git submodules

I don't really get what you saying but i think this should help you: `:Telescope git_files recurse_submodules=true show_untracked=false`.

Note: `show_untracked` has to be set to false because `git ls-files` which we use does not support both options. `--other` and `recurse_submodules`.

You can also just use `:Telescope find_files` which will uses `fd`, `rg` or `find` to list all files in cwd recursive. There is a `hidden` option so `:Telescope find_files hidden=true`
