### ISSUE TITLE
Additional builtins like - changing colorschemes and some git integrations.

### ISSUE THREAD

**Issue by singalhimanshu** [nvim-telescope/telescope.nvim#49]
For git integrations - [telescope-checkout](https://github.com/the-codingguy/telescope-checkout)

Idea for changing **colorscheme** - 
Show the current buffer in the preview window with the highlighted colorscheme.
**Note** - I don't have a clue about this preview thing with colorscheme. Is it feasible to do?

If you have any additional ideas or changes I can create a PR for both of these functionalities.

**Comment by tjdevries** [comment]
The colorscheme one seems hard at the moment, not sure how possible it would be to do.

The git  integrations one would be cool. We can make some git helper file that can do some of the common tasks that we want to do.

**Comment by the-codingguy** [comment]
> The colorscheme one seems hard at the moment, not sure how possible it would be to do.
> 
> The git integrations one would be cool. We can make some git helper file that can do some of the common tasks that we want to do.

Sure will do it. We can have a colorscheme one without a preview for now then?

**Comment by lithammer** [comment]
> We can have a colorscheme one without a preview for now then?

I don't really the point over something like `:color <tab>` with `wildmenu` enabled...?

**Comment by tjdevries** [comment]
Yeah, the colorscheme one is not as exciting.

The only thing I thought could be cool for it would be to open up neovim with the file name and the colorscheme in the preview as a separate process :laughing: 

The git ones provide a lot more interesting possiblities.

**Comment by Luxed** [comment]
👍 for the git integration!
I use this heavily for work and it's a life saver tbh. I personally use the following command: `git branch -r --sort=-committerdate --format="%(refname:lstrip=3)"` although it would be better if the current branch wasn't shown. Pressing `<CR>` simply does a checkout.
I also have one that does the same but for tags which is less important but still useful. I use this command for it: `git ls-remote -t --refs`.

> The only thing I thought could be cool for it would be to open up neovim with the file name and the colorscheme in the preview as a separate process 😆

Actually I think that could be an interesting idea!
There's something that I don't really like though: plugins and config. If you load a separate instance of neovim using the user's config, it could either take some time to load (which is fine since it would be async), but if there's any LSP integration or other heavy plugins, that would mean that processes would be spawned and killed a lot. I really don't have a lot of knowledge in this, but to me it seems like this could bring some issues along the way 😕

**Comment by the-codingguy** [comment]
@Luxed Thanks for the suggestions! For the `tags` one what action do you want to perform when the user presses `<CR>`

**Comment by Luxed** [comment]
> @Luxed Thanks for the suggestions! For the `tags` one what action do you want to perform when the user presses `<CR>`

I personally do a simple checkout. This way I'm in a "detached head" mode on the exact commit which makes it even better to test that "one weird bug the client's been having on this version".
So as I say earlier, this is a pretty special and specific use case.
Another thing to note is that the tags command takes a lot longer than the branches command to execute (which is the reason why I didn't combine both).

**Comment by tjdevries** [comment]
I'd like to close this issue and have issues raised for the individual items people are looking for (this way people can thumb up each post and what not if they are interested in having it). 

That will help me prioritize a lot better.

@the-codingguy can you make separate posts with the general idea for what you'd want for each of them?

**Comment by Luxed** [comment]
@tjdevries I'm actually working on adding them. I tried some things out and think I'm pretty happy with what I did in [my personal config](https://github.com/Luxed/nvim-config/blob/nightly-tests/lua/custom_telescope.lua).
I'll make a PR soon to add what I've made (at least as a starting point).
This is important to me, since it's basically the last finder holding me back :stuck_out_tongue:.
