### ISSUE TITLE
Set --hidden as default

### ISSUE THREAD

**Issue by beauwilliams** [nvim-telescope/telescope.nvim#525]
In my opinion 'hidden' files such as those in a .config directory should show by default

All files should show by default. It is up to the user to not show specific files.

This caused me quite a bit of headscratching until I realised this was the case.

**Comment by tami5** [comment]
Hmmm its quite difficult to make anything default without breaking stuff or go against user expectations. Personally, I used to have fuzzy finders with hidden enabled as default but since adopting telescope and having for example a away to create my own prompts (like browse dotfiles AND bin dir AND plugin dir) I haven't seen a need to enable hidden for my file finder. 

With that being said, hope you understand why this is something wouldn't be good to have as a default and you can always customize your personal version of telescope however you like. 

Thanks for sharing your thoughts.
