### ISSUE TITLE
Feature Request - (pop-up) menu to select from available actions

### ISSUE THREAD

**Issue by weilbith** [nvim-telescope/telescope.nvim#570]
**Is your feature request related to a problem? Please describe.**
Many of the available actions I use quite rarely. So I have issues to remember their key mappings. Especially when they differ depending on the chosen picker.

**Describe the solution you'd like**
Coming from Denite.nvim I would love to have the option to just remember one mapping that lets the user select from a list of all currently available actions.

**Describe alternatives you've considered**
Go from the currently open Telescope window to a new TMux tab, open NeoVim, open the Telescope help to checkout the help....

**Additional context**
Open for any visual realization approach. Pop-up preferably.

**Comment by fdschmidt93** [comment]
I think #1062 solved this problem sufficiently. Please see `:h actions.which_key` and/or `:h action_generate.which_key`.

I've realized there is a small thing off in the docs (doesnt impair functionality though) which I'll work right away on to fix. Please comment in case you have further comments. Otherwise closing this as part of cleanup.
