### ISSUE TITLE
Results don't respect ascii color codes? 

### ISSUE THREAD

**Issue by sefeng211** [nvim-telescope/telescope.nvim#616]
Hi! It looks like color codes aren't correctly displayed as colors in `Results`.

Here's the code that I used
```lua
local M = {}

local pickers = require('telescope.pickers')
local sorters = require('telescope.sorters')
local finders = require('telescope.finders')

M.taskoo_list_gtd_work = function()
        local results = vim.fn.system("echo '\\u001b[31mHelloWorld'")
        local split = vim.split(results, "\n")
        pickers.new {
          finder = finders.new_table(split),
          sorter = sorters.get_fuzzy_file(),
        }:find()
end

return M
```

**Actual Behaviour**:

When I run the above code, the `Results` list the item as `> ^[[31mHelloWorld`.

**Expected Behaviour**: `HelloWorld` displayed in red. 

Thanks!

**Comment by elianiva** [comment]
It won't do that because we don't interpret those escape sequences. If you want colours for your entries, you can still do that by using `entry_display.create` and bind a highlight group to the text. Take a look at this function for example.

https://github.com/nvim-telescope/telescope.nvim/blob/6e941e0ecec1ab6a1b4ce40c693ef1272c505abb/lua/telescope/make_entry.lua#L973

**Comment by yashLadha** [comment]
Happening too on my setup as well for default commands like `git_commits`
![image](https://user-images.githubusercontent.com/18033231/116014549-6c09a580-a653-11eb-93dc-0993c31c7610.png)
