### ISSUE TITLE
Toggle Preview Window

### ISSUE THREAD

**Issue by fedoranvar** [nvim-telescope/telescope.nvim#643]
**Is your feature request related to a problem? Please describe.**
It could be as distratction sometimes. Also, it could give a speed boost without window preview?

**Describe the solution you'd like**
To be able spawn telescope without preview window and to be able on hotkey toggle window preview

**Describe alternatives you've considered**
Right now I'm using fzf.vim for that

**Additional context**
nope

Thanks!

**Comment by elianiva** [comment]
you mean disabling previewer on-the-fly, as in, remove the previewer window? or do you want it to just be empty? I don't think the former is possible unless you close it first and then open it again without the previewer window. 

Maybe this is doable though. You'd make your own picker that can do that, bind a key to close/open with/without the previewer. You save your query that you typed in the prompt, and when you toggle the previewer (close the current one that has no previewer, open the other one that has a previewer) you'd use `feedkeys` to insert your previous query. (similar to how telescope-frecency handles the persistent tag-filter)

I don't know if that could work, I haven't try it myself, just thinking out loud :laughing:

**Comment by fedoranvar** [comment]
@elianiva I mean disabling on-the-fly, like fzf does

**Comment by TimUntersberger** [comment]
I would also appreciate it if you could disable the preview window and later on reenable it if needed.

Most of the time I already know what I am looking for specifically and only in rare cases I actually have to look at the preview.

> you mean disabling previewer on-the-fly, as in, remove the previewer window? or do you want it to just be empty? I don't think the former is possible unless you close it first and then open it again without the previewer window.

It should be possible to just not create the preview window at the start and later on just create it as long as there are no architectural problems (I haven't looked at the source code).

**Comment by Conni2461** [comment]
Hmm previewer side is easy. We can just always do `setup` (only initializes a state table) and previewing happens on selection and we can trigger that previewing with a single function call. (Doing that in the cycle previewer PR)

Hard part is what is expected from the layout. We would need to do some resizing (because only showing a empty window is kinda wasted space and boring, possible and easier to do but boring :laughing: ) and that would mean we would need to implement a dynamic resize interface in `popup.nvim` and `plenary.window.border`. If that is done then we have to figure out how to do the resizing general for each layout. Maybe we have to "build" on startup two layouts (positions, size, etc. because we have only a function that generates this dynamically) one for with and one for without previewer.

> like fzf does

Thats not possible because fzf is a cli tool that runs in a vim term. The whole gui is handled in go/cli land. So we have to figure out this one without looking at fzf :) Which could make it fun :laughing:

**Comment by ahmedelgabri** [comment]
I came here to open the same issue. Right now that's a major issue for me because I work in a big monorepo & it's very normal to have files that are 6-7 levels deep with long names & even similar names. With fzf I usually toggle preview depending on what I'm looking for & if I end up with multiple results with the same names etc… so having this option will be really great.

**Comment by FinallyFinancialFreedom** [comment]
I think the real problem is the find_files of git_files or live_grep result is too long , the result window only shows the paths, the filename is covered by preview window. The solution to this are:
1. wrap the result line, but it's ugly, difficult to view the result for human eyes.
2. toggle the preview window. it's elegant but difficult to implement.
3. like leaderf, show filename and path separately. show filename at the begin of the line, then the path. i think it's elegant and easy to implement, like https://github.com/nvim-telescope/telescope.nvim/wiki/Configuration-Recipes#customize-buffers-display-to-look-like-leaderf, btw i can not make this works because of  `cant find "vimrc.telescope.my_make_entry"` error.
4. an option for showing shorten path, like `U/d/p/filename.ext`, it's easy i think.
