### ISSUE TITLE
Could the file browser have broot style output?

### ISSUE THREAD

**Issue by alok** [nvim-telescope/telescope.nvim#712]
For keeping problem context clear in your head, using the file browser while viewing the directory structure too is really helpful.

**Comment by tami5** [comment]
\+1 I think it would be nice if you see the output of tree command for example :D.

**Comment by dccsillag** [comment]
I believe this would also be very helpful with the treesitter picker -- that way, instead of simply having a list of all the symbols in the current buffer with basically no organization, we could get them in a hierarchy, respecting the code organization (e.g., a class' method would appear inside of that class; a variable defined in a function would appear inside of the function).

**Comment by fdschmidt93** [comment]
I believe this is outside the project scope. How would you fuzzy search over a tree? This breaks the telescope setup of prompt, results, and a preview for a result. I guess what you are rather looking for is something like

https://github.com/simrat39/symbols-outline.nvim

**Comment by dccsillag** [comment]
> I guess what you are rather looking for is something like https://github.com/simrat39/symbols-outline.nvim

Yes, symbols-outline is pretty close to what I'd want, but the author appears to believe that this is outside of their scope, and has recommended using telescope instead: https://github.com/simrat39/symbols-outline.nvim/issues/51.

Personally, I agree that this is more in their camp, but since this is a reasonably related issue, which was open, I thought I'd try my luck.

> How would you fuzzy search over a tree? This breaks the telescope setup of prompt, results, and a preview for a result.

I'm not very familiar with telescope's abstractions, but [broot](https://github.com/Canop/broot) (which is in this issue's title) seems to do this quite well.

**Comment by fdschmidt93** [comment]
> I'm not very familiar with telescope's abstractions, but broot (which is in this issue's title) seems to do this quite well.

I'm afraid it still is outside of the scope of telescope. The results buffer is continuously updated. Hence, something like broot that fuzzy searches while persisting the layout would require very material changes to the backbone of telescope.

On that note, the file browser will be (hopefully some time this week) spun off into its own extension that will also have a folder browser to jump more easily across folders.

Closing this as wontfix.

**Comment by fdschmidt93** [comment]
With regards to the preview of the file browser (rather than the results buffer for e.g. treesitter), something like this will hopefully rather soonish be possible https://github.com/nvim-telescope/telescope-file-browser.nvim/pull/74
