### ISSUE TITLE
(Question) - Is this a neovim alternative to fzf.vim

### ISSUE THREAD

**Issue by supermacro** [nvim-telescope/telescope.nvim#719]
Just curious, is nvim-telescope a neovim-specific alternative to [fzf.vim](https://github.com/junegunn/fzf.vim)?

Any major differences between the two?

**Comment by Conni2461** [comment]
Yes and no.

`fzf` is a command line tool and `fzf.vim` is piping content (like buffers) to this external command and displays that command output in a split or floating window (depending which implementation you use).

`telescope.nvim` is a fuzzy finder over lists (that part is similar) but it runs in neovim. Its not an external process. We have up to 3 floating windows (prompt, results and preview). This comes with advantages and disadvantages.

Disadvantage: 
- `fzf` is a compiled go cli tool that can easily make use of goroutines to be async and super fast. For lua its not that easy to realize async but we are close to making telescope faster thanks to the effort here: https://github.com/nvim-lua/plenary.nvim/pull/83 and https://github.com/nvim-telescope/telescope.nvim/pull/709.

Advantage: 
- tight integration with neovim. That means the previewer will use vim buffer rather than invoking bat (we also have a bat previewer, and you can switch previewers as you want to). So this will result into the previewer having the same highlighting (treesitter or regex) than the buffer that will open.
- Also the architecture is pretty nice :laughing: You can replace everything. (swap out sorter, previewer, entry_maker (display/formatting of the entries) and more)

There are more differences but i just realize that i can just link tj youtube video :rofl: https://www.youtube.com/watch?v=8SqFt5h2Lsg and maybe primes https://www.youtube.com/watch?v=2tO2sT7xX2k
