### ISSUE TITLE
Hitting <CR> in any selection in telescope does not open the file

### ISSUE THREAD

**Issue by anderson-silva-concordia** [nvim-telescope/telescope.nvim#731]
### Description
When I open any Telescope window and select any result I can't open it hitting <CR>. Open in splits and in another tab is working fine.

**Expected Behavior**
That I could open the result hitting <CR>

**Actual Behavior**
The telescope window stay there, nothing happens. I can search and fuzzy find but can't open any result.

### Details

<details><summary>Reproduce</summary>

1. nvim .config/nvim/init.lua
2. :Telescope find_files
3. Select any file and hit <CR>
4. Notthing happens

</details>

<details><summary>Environment</summary>

```
NVIM v0.5.0-dev+1221-g9b2d4ff62
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az207-598
```
```
Manjaro Ornara 21.0
```
```
aefc831..d0cf646  master            -> origin/master
```
</details>

<details><summary>Configuration</summary>
<p>

```viml
set nocompatible hidden laststatus=2

if !filereadable('/tmp/plug.vim')
  silent !curl --insecure -fLo /tmp/plug.vim
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

source /tmp/plug.vim
call plug#begin('/tmp/plugged')
Plug 'nvim-lua/popup.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
call plug#end()

autocmd VimEnter * PlugClean! | PlugUpdate --sync | close
lua << EOF

require('telescope').setup{
  defaults = {
    vimgrep_arguments = {
      'rg',
      '--color=never',
      '--no-heading',
      '--with-filename',
      '--line-number',
      '--column',
      '--smart-case'
    },
    prompt_position = "bottom",
    prompt_prefix = ">",
    selection_strategy = "reset",
    sorting_strategy = "descending",
    layout_strategy = "horizontal",
    layout_defaults = {},
    file_ignore_patterns = {},
    shorten_path = true,
    winblend = 0,
    width = 0.75,
    preview_cutoff = 120,
    results_height = 1,
    results_width = 0.8,
    border = {},
    borderchars = { '─', '│', '─', '│', '╭', '╮', '╯', '╰'},
    color_devicons = true,
    use_less = true,
  }
}
EOF
```

**Comment by smithbm2316** [comment]
Hey @anderson-silva-concordia, you're still having this issue with the minimal config, not just when you run Neovim normally? Could you run the following commands and let me know what the output is?

```
:Telescope find_files
:verbose map <CR>
:verbose imap <CR>
```

Make sure to run the commands when the Telescope window is currently open please, thanks!

**Comment by anderson-silva-concordia** [comment]
:verbose map <CR>
```
n  <CR>        *@:<C-U>lua require('telescope.mappings').execute_keymap(8, 19)<CR>
        Last set from /tmp/plugged/telescope.nvim/plugin/telescope.vim
```

:verbose imap <CR>
```
i  <CR>         @<Plug>(PearTreeExpand)
        Last set from ~/.local/share/nvim/site/pack/packer/start/pear-tree/plugin/pear-tree.vim line 179
```

Hmmmm! Interesting! I removed my pearTree plugin and the folder that still had its reference and it's now working.

Thank you very much! It was super annoying not being able to hit <CR> to select anything

**Comment by smithbm2316** [comment]
@anderson-silva-concordia Not a problem! That's a *great* little trick to use if you're having any weird keymap issues, the `verbose` part will tell you exactly what file the mapping was attached in. I asked because I've had that *same exact issue* myself when I used to use PearTree! There actually is a workaround if you'd like that I used to use when I had PearTree installed! You can add the following line to disable PearTree for any Telescope prompt, add it to your `init.vim` or to your runtime path (I had this added in my nvim config in `after/plugin/pear-tree.vim`):
```vim
" pear-tree borks telescope's <CR> imap and other stuff
let g:pear_tree_ft_disabled = ['TelescopePrompt']
```
`after` is a directory that Vim automatically will source on startup, and `plugin` inside of the `after` directory will autosource whenever that plugin is loaded afaik. You can look both of those up in the help menus for more info on how they work, but basically I have all of my vimscript-based plugin configurations in their own files in `after/plugin/plugin-name.vim`. Makes it easy to keep track of and it gets auto-sourced after the plugins load! Let me know if you have any issues with that working for you, but this way you should be able to still use PearTree without it conflicting with Telescope!
