### ISSUE TITLE
Git stash picker

### ISSUE THREAD

**Issue by Shatur95** [nvim-telescope/telescope.nvim#799]
**Is your feature request related to a problem? Please describe.**
When working with a git, sometimes you have to work with stashes. 

**Describe the solution you'd like**
We already have a `git_commits` picker, this one can work similar. When you navigate to a stash, we can display their content in a preview, and when you press <CR>, apply it. We could also add other hotkeys to remove stash and pop it.

**Comment by amirrezaask** [comment]
I can work on this if no one has started yet

**Comment by Shatur95** [comment]
I accidentally noticed that my first message was not completely sent. Fixed it, sorry.

@amirrezaask, it would be awesome.

**Comment by amirrezaask** [comment]
https://github.com/nvim-telescope/telescope.nvim/pull/800
almost ok, only problem  is with the previewer that is not doing the highlighting I should investigate that, 
also for mappings
['<CR>'] = apply stash changes
suggest other mappings please

**Comment by Shatur95** [comment]
>  suggest other mappings please

How about `<C-d>` to drop stash and `<C-p>` for pop? Similar to [branches](https://github.com/nvim-telescope/telescope.nvim/blob/6fd1b3bd255a6ebc2e44cec367ff60ce8e6e6cab/lua/telescope/builtin/git.lua#L173).

**Comment by rudotriton** [comment]
`<C-n>` and `<C-p>` are used for scrolling so the latter is going to clash

**Comment by Shatur95** [comment]
> <C-n> and <C-p> are used for scrolling so the latter is going to clash

Ah, you are right. Then maybe `<C-o>`, not sure

**Comment by smithbm2316** [comment]
Just a note that `<C-d>` is a default binding in most pickers for scrolling the preview window down, so if you have a stash that is large and you want to scroll to see all its content in the preview window, this will conflict as well. I'm working at the moment on some updates to the docs to try and make some of these default mappings more obvious in #783, hopefully with additions there this will be more clear for future contributions! I love the idea of this picker, excited to see how it turns out!

**Comment by amirrezaask** [comment]
Previewer is fixed and applying is happening on `<CR>`  now
