### ISSUE TITLE
Make "ripgrep" a necessary dependency or highlight it's value

### ISSUE THREAD

**Issue by VolkovAK** [nvim-telescope/telescope.nvim#806]
Hello!
I am working as computer vision engineer, and I have multiple datasets with thousands of images in my project directory. I have installed Telescope and was completely frustrated by the speed of searching. Telescope tries to index all directories. Then I started to read relevant issues, documentation, even source code (despite I don't know lua). What I have found in my case:

1) default parameter "file_ignore_patterns" with command like this in init.vim
> :lua require('telescope').setup{ defaults = { file_ignore_patterns = {"data/", "datasets/" } } }

kind of works, but it just hides these directories from output while continue indexing.

2) "find_files" just ignores .gitignore, but seems like it should use this file.

3) "live_grep" does not work at all.

4) maps like
> nnoremap \<leader>ff :lua require("telescope.builtin").find_files{ find_command = { "rg", "--files", "--hidden", "--follow"} }<cr>

Shows nothing when I go with \<leader>ff (I have set up leader key properly)

So I have found that I need to install ripgrep to use "rg" in find_command (I just did know nothing about ripgrep and what is "rg", I thought it's a some inner-Telescope command), and at the same time all my issues were solved. But it's still unclear for me why it is an optional dependency when it gives such a huge improvement to user experience with Telescope and even allows to use live_grep.

My suggestion is to either force users to install ripgrep somehow, or at least emphasize this moment in README or somewhere else.

By the way, thanks for awesome tool!

**Comment by smithbm2316** [comment]
Hi @VolkovAK, thanks for the kind words and for the suggestion! I'm currently working on adding to and rewriting a decent amount of Telescope's documentation. I've added this to my list of improvements to make on the existing documentation. I don't think it's really in the interest of the primary maintainers of this project to make `ripgrep` a _required_ dependency, as Telescope is meant to be extensible and customizable first and foremost. However, I'll be happy to add a bit of extra documentation letting future users know about `ripgrep` and why it might be a useful tool to install with Telescope as well.

**Comment by aegatlin** [comment]
Hey @smithbm2316 thank your for the info and looking forward to the updated docs. 

I wanted to share a bit of UX feedback, having gone through a similar issue with not having had ripgrep installed and seeing nothing when I ran `telescope.live_grep`. The key distinction I wish was in the readme is: while ripgrep is an optional dependency, it is _also_ the default command for the `vimgrep` setting, and so anyone trying to "plug n play" telescope will get confused why live_grep is blank.

"An optional default" sounds like a nuance that is kind of hard to articulate in the docs, so good luck! :D I'd be happy to submit an small interim PR to the docs while the larger overhaul is in progress. Let me know.

**Comment by smithbm2316** [comment]
> Hey @smithbm2316 thank your for the info and looking forward to the updated docs.

Hey! I'm glad to hear the info was helpful. I'm sorry that there has not been much progress on adding this to the docs yet, I have been away from active work on this project for quite a little bit now. However, I will be back soon to work on this and other documentation that needs to be improved here in the coming weeks now that I've got some personal life things worked out that had been taking more of my time recently (I am starting a new job soon, had been going through the interview prep process pretty heavily).

> I wanted to share a bit of UX feedback, having gone through a similar issue with not having had ripgrep installed and seeing nothing when I ran `telescope.live_grep`. The key distinction I wish was in the readme is: while ripgrep is an optional dependency, it is _also_ the default command for the `vimgrep` setting, and so anyone trying to "plug n play" telescope will get confused why live_grep is blank.

This is great to know. I will keep that in mind as I add that to the documentation.

> "An optional default" sounds like a nuance that is kind of hard to articulate in the docs, so good luck! :D I'd be happy to submit an small interim PR to the docs while the larger overhaul is in progress. Let me know.

If you would like to do that, feel free! I have not started on this (as aforementioned) but plan to try and start some work on this later this week or the beginning of next week. I should have a PR thrown up by sometime next week, but I know this project always appreciates contributors if you feel so inclined to make that PR! Just ping me here if you do plan on doing that, otherwise I will plan to have that at the top of my todo list for my Telescope tasks here in the coming week.

**Comment by DonjiKong** [comment]
I cannot figure out how to use rp to use search with ripgrep. I installed it. 
noob here, how do this?
