### ISSUE TITLE
Duplicate "method" and "function" in Telescope treesitter

### ISSUE THREAD

**Issue by vpeopleonatank** [nvim-telescope/telescope.nvim#832]
# Describe:
When I use `:Telescope treesitter`, It show results by both "method" and "function" which is the same.
![image](https://user-images.githubusercontent.com/30976876/117598581-465fbe80-b172-11eb-81b5-df9f94f178e4.png)

# Expected behaviour:
Return only "method" or "function" in results.

**Comment by Conni2461** [comment]
Thats because the treesitter local queries are matching both `function` and `method` for class functions. Its not really an issue from us. We are just asking `treesitter-locals` for the results. You should probably report a bug to nvim-treesitter. Maybe the queries can be tweaked.
Also it doesn't make sense for us to deduplicate the table because we would need to each position, because names can appear multiple times, like `anchors`, etc ... 

(I think we should close this but i keep it open for tracking)

**Comment by vpeopleonatank** [comment]
> Thats because the treesitter local queries are matching both `function` and `method` for class functions. Its not really an issue from us. We are just asking `treesitter-locals` for the results. You should probably report a bug to nvim-treesitter. Maybe the queries can be tweaked.
> Also it doesn't make sense for us to deduplicate the table because we would need to each position, because names can appear multiple times, like `anchors`, etc ...
> 
> (I think we should close this but i keep it open for tracking)

Ok, thanks for clarification.
