### ISSUE TITLE
LSP Diagnostics - Sort by severity

### ISSUE THREAD

**Issue by theduke** [nvim-telescope/telescope.nvim#846]
**Is your feature request related to a problem? Please describe.**

Currently LSP diagnostics are mixed between different severity levels (hint, warning, error).

This is quite frustrating since the list might show many unimportant messages first, which makes it hard to focus on the errors.

**Describe the solution you'd like**

Add a custom sorter for diagnostics that first sorts the list by descending severity (error, warning, hint).

**Comment by smithbm2316** [comment]
If you check the docs with `:help telescope.builtin` and search for the `builtin.lsp_diagnostics` picker, it mentions that you can use the key mapping `<C-l>` to bring up a completion menu with different pre-filters to sort through all the diagnostics. I.e. you can type `:warning:` as a pre-filter and only see warnings from lsp in telescope and then refine your query from there.

**Comment by theduke** [comment]
Is there a way to supply this filter as an arugment in the invokation? Like `:Telescope lsp_workspace_diagnostics filter=:error"`?

But I will look into doing a PR.

**Comment by smithbm2316** [comment]
I do not know, I will look into finding out later today or tomorrow when I get the chance to peek at the source code for it!

**Comment by Conni2461** [comment]
There is `default_text` which works across all pickers but this is missing vim patches in neovim.

I have a workaround for this in #521 but i can't merge that yet because i am still waiting for something from tj. (But i just rebased it so you could use it).

Also grouping group by severity doesn't seems to be a bad idea. If you want to do it `lua/telescope/utils.lua` search for `diagnostics_to_tbl`. I think thats a good starting point

**Comment by pidgeon777** [comment]
It seems that `:error:` filter is not available in `lsp_document_diagnostic`, is there any plan\way to support it?

**Comment by Conni2461** [comment]
@pidgeon777 Works fine with `clangd`. As far as i remember it only lets you filter for diagnostics that are currently actually in the list. Which languageserver do you use?
