### ISSUE TITLE
Feat: Add option to easily toggle tree-sitter based highlighting 

### ISSUE THREAD

**Issue by shaunsingh** [nvim-telescope/telescope.nvim#857]
**Is your feature request related to a problem? Please describe.**
There have recently been a few bugs in treesitter (mainly https://github.com/tree-sitter/tree-sitter/issues/973#issuecomment-810480327, that greatly increases the loading times for certain filetypes 
 
For example, kotlin files can take upto two seconds to load. While this is somewhat bearable when opening singular files, when browsing through 10's of files it can take quite a while. 

**Describe the solution you'd like**
At the moment, the README discusses that treesitter is an optional dependency and can be used for syntax highlighting, but doesn't mention how to disable it. Adding either an option or more information to the README would be a good change 

**Additional context**
When searching for certain filetypes (e.g. php and kotlin) neovim will freeze for 1-2 seconds while the file loads.

**Comment by johnobla** [comment]
I respectfully disagree with this feature request.

Since Treesitter is an optional dependency and isn't included with Telescope, Telescope doesn't use Treesitter if it's not installed.

Similar to the ripgrep optional dependency, Telescope feels amazing when it "just works" with Treesitter.

It would be disappointing if this feature request removed that amazing feeling for newcomers to Telescope.

**Comment by shaunsingh** [comment]
I understand your stance on the issue, but shouldn't we favor form over function? As much as I like the beautiful look of treesitter, a fuzzy finders first and foremost job should be fast file searching, the nice colors should come second.

**Comment by johnobla** [comment]
I agree completely. I also understand the frustration that comes with laggy loading, after all it's why we're here and not on VSCode 🙂

Our differing opinions come from changing the default functionality, rather than choosing form over function.

Right now the default functionality says:
1. If you don't already have Treesitter installed, I won't touch it
2. If you already have Treesitter installed, I'll use it to make your previews prettier

With the feature request, we'd be  changing the default functionality to cater to those who
1. Have Treesitter installed and benefit from its syntax highlighting
2. But don't want the syntax highlighting applied when searching for files

This is a group that should be catered for (just like any other), just not as the default option for Telescope.

**Comment by shaunsingh** [comment]
You're right. I think an option would be better than changing the defaults.

**Comment by Conni2461** [comment]
Its already possible. Not as user friendly, but way more flexible. You can do different things like highlight only certain filetypes with regex and other default.

Related threads (first):
- https://github.com/nvim-telescope/telescope.nvim/issues/623#issuecomment-792233601
- https://github.com/nvim-telescope/telescope.nvim/issues/223#issuecomment-810091610

And here is the snippet you are looking for:

```lua
local previewers = require('telescope.previewers')
local putils = require('telescope.previewers.utils')
local pfiletype = require('plenary.filetype')

local new_maker = function(filepath, bufnr, opts)
  opts = opts or {}
  if opts.use_ft_detect == nil then
    local ft = pfiletype.detect(filepath)
    -- Here for example you can say: if ft == "xyz" then this_regex_highlighing else nothing end
    opts.use_ft_detect = false
    putils.regex_highlighter(bufnr, ft)
  end
  previewers.buffer_previewer_maker(filepath, bufnr, opts)
end

require('telescope').setup {
  defaults = {
    buffer_previewer_maker = new_maker,
  }
}
```

I hope i haven't forgotten something in that snippet. I think this is way more powerful than just having a config option. But maybe we should put these configurations in the wiki

**Comment by clason** [comment]
Also, as data points:

1. Tree-sitter is not all or nothing; it might work great for one language but not for another, even if I have the parser installed for testing purposes. So if _I_ don't activate tree-sitter based highlighting, I don't want telescope to do it for me, either.
2. Tree-sitter is still declared as experimental for the upcoming neovim 0.5. This is another argument to make it opt-in in telescope.

**Comment by shaunsingh** [comment]
Since the issue is only with select languages, an option to blacklist languages would be a possible solution, but that might be a little too complicated and unnecessary. 
> https://github.com/nvim-telescope/telescope.nvim/issues/857#issuecomment-846368690
Thanks, that worked like a charm for now!

**Comment by fdschmidt93** [comment]
I haven't read the entire thread, but you can now turn off treesitter entirely or only opt in to specific filetypes. 

Please see `:h telescope.defaults.preview` on how to do that at `telescope.setup`. Feel free to ping me/reopen in case there's issues.

**Comment by shaunsingh** [comment]
Been using an experimental kotlin parser, eveeything is far faster now, good enough to just keep treesitter enabled all the time!

Thanks for the follow up though
