### ISSUE TITLE
Builtin git_files treats all directories as git repos

### ISSUE THREAD

**Issue by dstanberry** [nvim-telescope/telescope.nvim#861]
### Description

The snippet taken from https://github.com/nvim-telescope/telescope.nvim/wiki/Configuration-Recipes#falling-back-to-find_files-if-git_files-cant-find-a-git-directory fails when the current path is not a git directory.

```lua
local M = {}

M.project_files = function()
  local opts = {} -- define here if you want to define something
  local ok = pcall(require'telescope.builtin'.git_files, opts)
  -- print value
  print(vim.inspect(ok))
  if not ok then require'telescope.builtin'.find_files(opts) end
end

return M
```

**Expected Behavior**

`ok` should evaluate to false when pwd/cwd is not a git directory

**Actual Behavior**

The value of `ok` seems to be `true` when pwd/cwd is not a git directory.

### Details

<details><summary>Reproduce</summary>

1. cd /tmp/ # ... and copy configuration below to test.vim
2. nvim -nu test.vim
3. press `<space><space>` in normal mode
</details>

<details><summary>Environment</summary>

- nvim --version output:
NVIM v0.5.0-dev+1323-gd67dcaba0-dirty
Build type: Gentoo
LuaJIT 2.0.5
- Operating system: 
Gentoo
- Telescope commit: 
69eb5ea

</details>

<details><summary>Configuration</summary>
<p>

```viml
set nocompatible hidden laststatus=2

if !filereadable('/tmp/plug.vim')
  silent !curl --insecure -fLo /tmp/plug.vim
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

source /tmp/plug.vim
call plug#begin('/tmp/plugged')
Plug 'nvim-lua/popup.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
call plug#end()

autocmd VimEnter * PlugClean! | PlugUpdate --sync | close
lua << EOF

require('telescope').setup{
  defaults = {
    vimgrep_arguments = {
      'rg',
      '--color=never',
      '--no-heading',
      '--with-filename',
      '--line-number',
      '--column',
      '--smart-case'
    },
    prompt_position = "bottom",
    prompt_prefix = ">",
    selection_strategy = "reset",
    sorting_strategy = "descending",
    layout_strategy = "horizontal",
    layout_defaults = {},
    file_ignore_patterns = {},
    shorten_path = true,
    winblend = 0,
    width = 0.75,
    preview_cutoff = 120,
    results_height = 1,
    results_width = 0.8,
    border = {},
    borderchars = { '─', '│', '─', '│', '╭', '╮', '╯', '╰'},
    color_devicons = true,
    use_less = true,
  }
}

-- taken from https://github.com/nvim-telescope/telescope.nvim/wiki/Configuration-Recipes#falling-back-to-find_files-if-git_files-cant-find-a-git-directory

_G.project_files = function()
  local opts = {} -- define here if you want to define something
  local ok = pcall(require'telescope.builtin'.git_files, opts)
  if not ok then require'telescope.builtin'.find_files(opts) end
end

EOF

nmap <silent> <space><space> :call v:lua.project_files()<cr>


```

**Comment by joelpalmer** [comment]
That wiki snippet stopped working for me a couple weeks ago. I don't recall which commit this repo or dependencies were on at the time. I wrote this to keep that functionality in place for me. There is probably a better way but it works. 

```lua
M.project_files = function()
	local _, ret, stderr = utils.get_os_command_output({ 'git', 'rev-parse', '--is-inside-work-tree' })
	local gopts = {}
	gopts.prompt_title = 'Git Files'
	gopts.prompt_prefix = '  >  '
	if ret == 0 then 
		require'telescope.builtin'.git_files(gopts)
	else
		require'telescope.builtin'.find_files()
	end
end

```

**Comment by jose-elias-alvarez** [comment]
I think the issue is caused by [this check](https://github.com/nvim-telescope/telescope.nvim/blob/b06e17e4a1b59a0a39863e6fa38fc83020b826e7/lua/telescope/builtin/git.lua#L269), which was added in 0d6cd47990781ea760dd3db578015c140c7b9fa7. The check is pretty broken, since `is_worktree` is actually a list containing `stdout`, so the condition `is_worktree == "false"` will never be true. 

Moreover, `git rev-parse --is-inside-work-tree` only seems to return `false` in a bare Git repository. In a regular non-Git directory, it'll output `fatal: not a git repository (or any of the parent directories): .git` to `stderr`, so `is_worktree` will just be an empty table, since `stdout` will be empty. 

I can imagine a few solutions, but a simple one that seems to work for both bare repos and non-Git directories is changing the condition to `is_worktree[1] == "false" or not is_worktree[1]` (though the variable name then becomes somewhat misleading). Happy to put in a quick PR if this is solution is on the right track.

**Comment by Conni2461** [comment]
Yep the check is just wrong. Pr welcome :)
