### ISSUE TITLE
fzy_native or fzf_native

### ISSUE THREAD

**Issue by sriramkandukuri** [nvim-telescope/telescope.nvim#894]
Hi,

I am browsing through repos of nvim-telescope.
And curious about what to use for fzf native plugin?

Do I need to use fzy_native or fzf_native ?

Thanks,
Sriram.K

**Comment by tami5** [comment]
Try them both and see which algorithm befit you. fzf_native is faster, thanks to @Conni2461 continuous development.

**Comment by sriramkandukuri** [comment]
Yeah tried both, fzf_native is faster. But if feel it is slower than original fzf.vim from junegunn when number of files is more.

**Comment by Conni2461** [comment]
Yeah junegunn's fzf will probably always be faster because everything is compiled. 

For the native sorters we only compile "1 function" `(ordinal, prompt) -> (score)`, so sorting and everything is still happening in lua, mostly single threaded. We have some work with coroutines so you can still type when we calculate stuff. Junegunn can just use goroutines because fzf is a CLI tool (which can be put in a vim/nvim terminal window).

Note `fzf_native` is also a from scratch port to c and its super hard to actually compare only the scoring algorithm because `fzf` is really tightly coupled.
