### ISSUE TITLE
Yarn workspaces support for lsp_references

### ISSUE THREAD

**Issue by vuki656** [nvim-telescope/telescope.nvim#896]
**Is your feature request related to a problem? Please describe.**

Currently, if you have a project setup up with yarn workspaces, `lsp_implementations` doesn't work as expected.

For example, if you have two modules in the workspace, module `A` and module `B`.  You define something in module `A`, and then use it in module `B`. Then if you go to module `A` where that thing was defined, and try to find references with `lsp_implementations` it won't provide any results.

Interestingly enough, it works the other way around, If you go to the place where it is used, and try to go to its definition with `lsp_definitions` it will work. 

**Describe the solution you'd like**

For the `lsp` related actions to be able to interact with yarn workspaces. As in the example below, it would be able to find the implementations of something in other `yarn workspace`

**Comment by Conni2461** [comment]
Which languageserver are you using? https://github.com/theia-ide/typescript-language-server ? Because this server doesn't have `textDocument/implementation` support as far as i can see.

Also we don't really do anything with lsp. We are only requesting from lsp and displaying it. If we don't get results back the protocol is either not supported in your lsp server or neovim lsp implementation is missing something. The issue is rarely here

**Comment by vuki656** [comment]
You're right, sorry for spamming.
