### ISSUE TITLE
Picker a la `builtin` but that also includes custom pickers

### ISSUE THREAD

**Issue by VVKot** [nvim-telescope/telescope.nvim#925]
**Is your feature request related to a problem? Please describe.**
Telescope is great but at this point there are *lots* of pickers. This why `builtin` picker is amazing, I can bind one short cut and have easy access to all 49 (!) default pickers.

However, there is a problem. Custom pickers (see below) that are popping up are *not* included in this picker, which makes for a frustrating experience.

https://github.com/folke/todo-comments.nvim
https://github.com/folke/trouble.nvim
https://github.com/fhill2/telescope-ultisnips.nvim

**Describe the solution you'd like**
A picker, either (renamed) builtin or a new one, that *does* include custom pickers. I would imagine all that needs to be done is exposing some plugin-like endpoint in telescope for pickers to "register" them - but I might be wrong.

**Describe alternatives you've considered**
I either do `:Telescope <Tab>` or bind a specific mapping for custom pickers, which is not ideal.

**Additional context**
I am not sure why but autocompletion in `:Telescope <Tab>` *does* recognize custom pickers.

**Comment by Conni2461** [comment]
The most baffling thing about that issue is the number 49. WTF 49. GG all to all 107 Contributors. (What will number 50 be)

`:Telescope <Tab>` dispatches to lua calls dynamically and looks at the registered_extensions https://github.com/nvim-telescope/telescope.nvim/blob/6ac5ee0854fe02d651cadf2fc97a2463ff92f322/lua/telescope/_extensions/init.lua#L24-L52

So what you suggest is already possible. Someone would need to extend `builtin.builtin` accordingly (shouldn't be that hard). But the action might need some changes too and i am currently not sure if the previewer would work with the _extensions in the table. My guess is no it doesn't work. But we can just write someone like "Extension code is hidden and closed source 🤣" or so.

The only problem i see with adding this feature is the name `builtin.builtin` (and we can't really change it) and i don't want another picker for that (50 needs to be something amazing), so an option?! Just rambling right now
