### ISSUE TITLE
Fzf-native fuzzy searching doesn't work with lsp_dynamic_workspace_symbols picker?

### ISSUE THREAD

**Issue by jesseleite** [nvim-telescope/telescope.nvim#926]
### Description

Fzf-native fuzzy searching doesn't seem to work with lsp_dynamic_workspace_symbols picker.

**Expected Behavior**

I do notice fuzzy searching works with the other lsp_document_symbols finder, and would expect it to work the same with the lsp_dynamic_workspace_symbols finder.

![image](https://user-images.githubusercontent.com/5187394/122587800-42a24000-d02c-11eb-908d-a3aaf1bcf6ef.png)

**Actual Behavior**

Fuzzy search for a method you know exists. In my case, I have a `setInBlueprints` method that I can't see when fuzzy searching:

![image](https://user-images.githubusercontent.com/5187394/122587611-0969d000-d02c-11eb-9851-6e0e33285b68.png)

But I do see it if I search for the exact method name:

![image](https://user-images.githubusercontent.com/5187394/122587643-11c20b00-d02c-11eb-9100-9a864f4c5164.png)

### Details

<details><summary>Reproduce</summary>

1. nvim -nu test.vim
2. 
3. 
</details>

<details><summary>Environment</summary>

- nvim --version output: 
- Operating system: 
- Telescope commit: 

</details>

<details><summary>Configuration</summary>
<p>

```viml
set nocompatible hidden laststatus=2

if !filereadable('/tmp/plug.vim')
  silent !curl --insecure -fLo /tmp/plug.vim
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

source /tmp/plug.vim
call plug#begin('/tmp/plugged')
Plug 'nvim-lua/popup.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
call plug#end()

autocmd VimEnter * PlugClean! | PlugUpdate --sync | close
lua << EOF

require('telescope').setup{
  defaults = {
    vimgrep_arguments = {
      'rg',
      '--color=never',
      '--no-heading',
      '--with-filename',
      '--line-number',
      '--column',
      '--smart-case'
    },
    prompt_position = "bottom",
    prompt_prefix = ">",
    selection_strategy = "reset",
    sorting_strategy = "descending",
    layout_strategy = "horizontal",
    layout_defaults = {},
    file_ignore_patterns = {},
    shorten_path = true,
    winblend = 0,
    width = 0.75,
    preview_cutoff = 120,
    results_height = 1,
    results_width = 0.8,
    border = {},
    borderchars = { '─', '│', '─', '│', '╭', '╮', '╯', '╰'},
    color_devicons = true,
    use_less = true,
  }
}
EOF
```

**Comment by Conni2461** [comment]
`lsp_dynamic_workspace_symbols` follows the same idea as `live_grep` so there is no sorter attached (besides highlighting)

**Comment by jesseleite** [comment]
What are your thoughts on giving it a sorter, even if a basic one for the purpose of allowing fuzzy searching via fzf-native, etc?

**Comment by Conni2461** [comment]
You can always set your own sorter. `lua require("telescope.builtin").find_files { sorter = require("telescope").extensions.fzf.native_fzf_sorter }`

But for `live_grep` and `lsp_dynamic_workspace_symbols` this doesn't work because the prompt goes instantly to `vim.lsp.buf_request(bufnr, "workspace/symbol", {query = prompt}, tx)`. It would be cool to introduce something like stage_grep from fzf_writer buts its harder to do if you can't use a pipe. So we would need some changes here somewhere :rofl: But i currently don't have the time to implement them ;)

Also dynamic was only introduced to work around some issues with certain lsps. For example clangd requires a query so you can't get all symbols with using "" as query. Also rust-analyzer doesn't show functions with query "" i think you need to start with # to only show functions here.

If your lsp supports it (i don't know php) you might just wanna give `Telescope lsp_workspace_symbols` a shot which uses query "" as default and might just get you all workspace symbols upfront (its not async so it blocks neovim, which sucks but yeah, i am pretty sure ober or tj will change it now that async2 is done). Or you do `Telescope lsp_workspace_symbols query=asdf`


Just a thought: we could use this issue to track a staged grep / staged lsp_dynamic_workspace_symbols. Which supports live upfront then special character and then fuzzy over live results. (But i would just extend the current builtins rather than introducing a new builtin)

**Comment by Conni2461** [comment]
It shouldnt suppose to work. Not an issue
Currently work on this: https://github.com/nvim-telescope/telescope.nvim/issues/1590

So i am closing this because #1590 is more general.
