### ISSUE TITLE
Windows: Calling shorten_dir via ffi doesn't seem to work

### ISSUE THREAD

**Issue by Nazeehe** [nvim-telescope/telescope.nvim#968]
### Description

Trying to use the new "shorten" feature of path_display on Windows 10, NeoVim 0.5 release. I get an error in nvim when launching Telescope find_files saying that "shorten_dir" symbol is unspecified. 

Looking at the code, it uses ffi module to call the NeoVim internal function shorten_dir. Seems that this does not work on Windows?

**Comment by Conni2461** [comment]
We just switched over to `plenary.path` and its `shorten_dir` implementation. We already disabled the ffi code over there for windows and replaced it with a lua solution. Might be slower but should work for now.

It seems like that adding `__declspec(dllexport)` to those functions should solve that problem on windows. If that happens we will enable the ffi code for windows again :)

Can you confirm that this issue is now fixed?

**Comment by Nazeehe** [comment]
Confirmed! Works fine on Windows. Thanks for the prompt fix.
