### ISSUE TITLE
File mask in live_grep

### ISSUE THREAD

**Issue by igor-semenov** [nvim-telescope/telescope.nvim#997]
**Is your feature request related to a problem? Please describe.**
I'd like to use live_grep to search through specific file types in project, for example, C++ source files. But usual live_grep searches in all of files.

**Describe the solution you'd like**
Maybe a parameter in live_grep, specifying file masks, for example: *.h,*.cpp

**Describe alternatives you've considered**
I'm using ag for now.

**Comment by Nazeehe** [comment]
I like this idea. I messed around the code a bit and have this working:

Telescope live_grep grep_args=-tcs

this passes -tcs to Rg and scopes the search down to C# files only. For Ag, that would be:

Telescope live_grep grep_args=--csharp

Thoughts on this pattern?

**Comment by igor-semenov** [comment]
I tried your solution:
`:Telescope live_grep grep_args=-tcpp`
but unfortunately it doesn't work for me, live_grep still searches in all of files, not in C++ sources.

**Comment by Nazeehe** [comment]
Hey @igor-semenov, I have changed the PR (which you would need to apply to your branch as it's not checked in yet). When it's checked in (waiting on approval), you would add something like this to your telescope config:

``` lua
require("telescope").setup {
  defaults = { 
    -- your defaults for telescope
  },
  pickers = {
    live_grep = {
      -- your defaults for live_grep
        additional_args = function(opts)
            if opts.search_all == true then
                return {}
            end

            local args_for_ext = {
                ["cs"]  = "-tcs",
                ["cpp"] = "-tcpp",
                ["c"]   = "-tcpp",
                ["h"]   = "-tcpp",
                ["rs"]  = "-trust",
                ["lua"] = "-tlua"
            }
            return { args_for_ext[vim.bo.filetype] }
        end
    }
  }
}
```
This would make it so that when you run ":Telescope live_grep", live_grep code will call this function. This function is meant to add extra args to be passed to Rg. This particular function here will read the filetype of the buffer you're on now and will use the lookup table to match the args to the type. So in your case, if the buffer you're on is .cpp, it will add -tcpp to Rg. If you switch to a buffer with .rs, it will automatically add -trust. That's just my implementation of the feature using this function, you can do whatever you want of course.

**Comment by igor-semenov** [comment]
@Nazeehe thank you for the explanation!

**Comment by Nazeehe** [comment]
> @Nazeehe thank you for the explanation!

Hey @igor-semenov, PR is in. Feel free to add the code I posted earlier to your configuration and you should get the functionality you need. Feel free to change that custom function to suite your needs :)

**Comment by fdschmidt93** [comment]
Closing this as I think this issue is solved. I'll write a note for myself to check on this so it's maybe properly highlighted in docs rework (if applicable) as I'm unaware of the PR but skimming makes me think this helps on a few other issues.

Internet is down, doing clean up on mobile 😅
